<#
.SYNOPSIS
    Throwaway probe that measures Unity's managed-plug-in reimport loop.

.DESCRIPTION
    Issue #5 calls the DLL edit/rebuild/see-it loop "the single highest-value
    thing for the walking skeleton to establish in its first hour -- the
    difference between a 3-second loop and a 40-second one", and issue #15
    asks issue #10 to record it. But there is no sim/ project yet, so there is
    nothing to rebuild.

    This stands in for it. Unity's reimport behaviour does not depend on what
    is inside an assembly, so a three-line stub answers the timing question
    identically -- provided it sits in the same KIND of place the real sim
    will, which is why this is an embedded UPM package targeting
    netstandard2.1 with no engine reference, exactly as issue #15 decided.

    It is deliberately NOT named Sim, so it can never be confused with the
    real plug-in, and client/.gitignore refuses to commit any of its files.

    NOTE: while installed, the probe WILL show up in the tracked file
    client/Packages/packages-lock.json, which .gitignore cannot prevent.
    That diff is expected -- never commit it. See issue #29.

.EXAMPLE
    ./tools/hotreload-probe/probe.ps1 -Install
    Creates the package, builds it, drops the Editor logger in. Run once,
    after the Unity project exists.

.EXAMPLE
    ./tools/hotreload-probe/probe.ps1 -Bump
    Rebuilds with a fresh stamp. This is the measurement: run it, note the
    time, alt-tab to Unity, and watch the Console for the new stamp.

.EXAMPLE
    ./tools/hotreload-probe/probe.ps1 -Remove
    Deletes every trace of the probe.
#>
[CmdletBinding(DefaultParameterSetName = 'Bump')]
param(
    [Parameter(ParameterSetName = 'Install')][switch]$Install,
    [Parameter(ParameterSetName = 'Bump')][switch]$Bump,
    [Parameter(ParameterSetName = 'Remove')][switch]$Remove
)

$ErrorActionPreference = 'Stop'

$RepoRoot    = (Get-Item $PSScriptRoot).Parent.Parent.FullName
$Client      = Join-Path $RepoRoot 'client'
$PackageDir  = Join-Path $Client 'Packages/com.ssalter.hotreloadprobe'
$RuntimeDir  = Join-Path $PackageDir 'Runtime'
$CounterFile = Join-Path $PackageDir '.counter'
# The logger lives INSIDE the package, so every file the probe generates sits
# under the one directory client/.gitignore already refuses. Putting it in
# Assets/Editor/ instead made Unity generate an Assets/Editor.meta that no
# ignore rule covered, so `git add -A` would have committed a trace of the
# probe -- the exact leak this probe is supposed to be incapable of.
$EditorDir   = Join-Path $PackageDir 'Editor'
$EditorDest  = Join-Path $EditorDir 'HotReloadProbeLog.cs'
# Where -Install used to put it. -Remove still clears this so an install made
# by the older script is cleaned up rather than left behind.
$LegacyDir   = Join-Path $Client 'Assets/Editor'
$LegacyDest  = Join-Path $LegacyDir 'HotReloadProbeLog.cs'
$SrcDir      = Join-Path $PSScriptRoot 'src'
$ProbeCs     = Join-Path $SrcDir 'Probe.cs'
$EditorSrc   = Join-Path $PSScriptRoot 'editor/HotReloadProbeLog.cs'

function Assert-UnityProject {
    foreach ($d in @('Assets', 'ProjectSettings')) {
        if (-not (Test-Path (Join-Path $Client $d))) {
            throw ("No Unity project at $Client (missing $d/).`n" +
                   "Create the project first -- step 4 of issue #10 -- then run -Install.")
        }
    }
}

function Write-ProbeSource([int]$Number) {
    $when  = Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'
    $stamp = "build #$Number at $when"
    @"
// GENERATED by tools/hotreload-probe/probe.ps1 -- do not edit, it is overwritten.
namespace HotReloadProbe
{
    /// <summary>Throwaway. Exists only to carry a stamp that changes on rebuild.</summary>
    public static class Probe
    {
        public static string Stamp = "$stamp";
    }
}
"@ | Set-Content -Path $ProbeCs -Encoding utf8
    return $stamp
}

function Build-Probe([int]$Number) {
    $stamp = Write-ProbeSource $Number
    $sw = [Diagnostics.Stopwatch]::StartNew()
    & dotnet build $SrcDir -c Debug -o $RuntimeDir --nologo -v quiet
    if ($LASTEXITCODE -ne 0) { throw "dotnet build failed with exit code $LASTEXITCODE." }
    $sw.Stop()

    # Unity has no use for these and would import them as assets.
    Get-ChildItem $RuntimeDir -Filter '*.deps.json' -ErrorAction SilentlyContinue |
        Remove-Item -Force -ErrorAction SilentlyContinue

    Set-Content -Path $CounterFile -Value $Number -Encoding utf8
    [pscustomobject]@{ Stamp = $stamp; BuildMs = [int]$sw.Elapsed.TotalMilliseconds }
}

if ($Install) {
    Assert-UnityProject

    New-Item -ItemType Directory -Force -Path $RuntimeDir | Out-Null
    New-Item -ItemType Directory -Force -Path $EditorDir  | Out-Null

    @'
{
  "name": "com.ssalter.hotreloadprobe",
  "version": "0.0.0",
  "displayName": "Hot-reload probe (throwaway)",
  "description": "Throwaway. Measures how long Unity takes to notice a rebuilt managed plug-in. This is NOT the sim -- see tools/hotreload-probe/. Delete with probe.ps1 -Remove.",
  "unity": "6000.3"
}
'@ | Set-Content -Path (Join-Path $PackageDir 'package.json') -Encoding utf8

    # Code inside a package is not compiled without an assembly definition --
    # unlike code under Assets/, it never joins Assembly-CSharp-Editor.
    @'
{
  "name": "HotReloadProbe.Editor",
  "rootNamespace": "",
  "references": [],
  "includePlatforms": [ "Editor" ],
  "autoReferenced": true
}
'@ | Set-Content -Path (Join-Path $EditorDir 'HotReloadProbe.Editor.asmdef') -Encoding utf8

    Copy-Item $EditorSrc $EditorDest -Force

    $r = Build-Probe 1

    Write-Host ""
    Write-Host "Probe installed." -ForegroundColor Green
    Write-Host "  package : client/Packages/com.ssalter.hotreloadprobe/"
    Write-Host "  editor  : client/Packages/com.ssalter.hotreloadprobe/Editor/HotReloadProbeLog.cs"
    Write-Host "  stamp   : $($r.Stamp)   (dotnet build took $($r.BuildMs) ms)"
    Write-Host ""
    Write-Host "Now switch to Unity and let it import. You should see a line in the"
    Write-Host "Console beginning [hot-reload probe]. Then run -Bump to measure."
    exit 0
}

if ($Remove) {
    # Everything a current install generates is inside the package, so removing
    # it is one delete. The rest clears an install made by the older layout,
    # which put the logger under Assets/Editor/.
    foreach ($p in @($PackageDir, "$PackageDir.meta", $LegacyDest, "$LegacyDest.meta")) {
        if (Test-Path $p) { Remove-Item $p -Recurse -Force; Write-Host "removed $p" }
    }
    if ((Test-Path $LegacyDir) -and -not (Get-ChildItem $LegacyDir -Force)) {
        Remove-Item $LegacyDir -Force
        if (Test-Path "$LegacyDir.meta") { Remove-Item "$LegacyDir.meta" -Force }
        Write-Host "removed $LegacyDir (was empty)"
    }
    Remove-Item (Join-Path $SrcDir 'bin'), (Join-Path $SrcDir 'obj'), $ProbeCs `
        -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "Probe removed." -ForegroundColor Green
    Write-Host ""
    Write-Host "Let Unity refresh once, then check: client/Packages/packages-lock.json" -ForegroundColor Yellow
    Write-Host "should go back to clean on its own. If it still names" -ForegroundColor Yellow
    Write-Host "com.ssalter.hotreloadprobe, do NOT commit it -- see issue #29." -ForegroundColor Yellow
    exit 0
}

# -Bump (the default)
if (-not (Test-Path $PackageDir)) {
    throw "Probe is not installed. Run: ./tools/hotreload-probe/probe.ps1 -Install"
}

$n = 1
if (Test-Path $CounterFile) { $n = [int](Get-Content $CounterFile -Raw).Trim() + 1 }

$r = Build-Probe $n

Write-Host ""
Write-Host "Rebuilt at $(Get-Date -Format 'HH:mm:ss.fff')  --  $($r.Stamp)" -ForegroundColor Green
Write-Host "dotnet build: $($r.BuildMs) ms"
Write-Host ""
Write-Host "Alt-tab to Unity NOW and start counting. Record, on issue #10:"
Write-Host "  1. Does the new stamp appear on focus alone, with no other action?"
Write-Host "  2. How many seconds from alt-tab to the Console line?"
Write-Host "  3. Repeat with Play mode RUNNING -- does it reload, refuse, or"
Write-Host "     does the build fail with access-denied because Unity holds the DLL?"
Write-Host "  4. If nothing happens, try Ctrl+R (Assets > Refresh), then an"
Write-Host "     Editor restart -- and note which one was actually needed."
