using System;
using System.Collections.Generic;
using System.Globalization;

namespace Sim
{
    /// <summary>
    /// A recorded run's rolling state hash, one entry per tick, to check a live
    /// run against as it goes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Per tick, not at the end.</b> An end-of-match comparison answers "did
    /// this run match" with a yes or a no, and a no is nearly useless: the
    /// divergence could be anywhere in two thousand ticks and it has had the
    /// whole match to contaminate everything downstream. Checking every tick
    /// answers "which tick", which is the answer somebody can act on -- and it
    /// costs one comparison per tick to get.
    /// </para>
    /// <para>
    /// What is being compared is <b>internal simulation state, not the
    /// snapshot</b>: accumulated fixed-point remainders, the position of the
    /// single dice stream, and how target-selection ties were broken. Those are
    /// exactly the fields a view never needs and exactly the ones likeliest to
    /// drift, so a divergence in a field nothing draws is still caught here.
    /// </para>
    /// <para>
    /// The file is generated by a real run and committed. It is deliberately not
    /// generated by whatever is checking it -- a trace written by the run it
    /// validates is a test that cannot fail.
    /// </para>
    /// </remarks>
    public sealed class GoldenTrace
    {
        private const string Keyword = "tick";

        /// <summary>Fields per row, keyword included.</summary>
        private const int FieldCount = 3;

        private readonly ulong[] _hashes;

        private GoldenTrace(ulong[] hashes)
        {
            _hashes = hashes;
        }

        /// <summary>How many ticks the trace covers, counting tick zero.</summary>
        public int Count => _hashes.Length;

        /// <summary>The last tick in the trace, which is the tick the match ended on.</summary>
        public int FinalTick => _hashes.Length - 1;

        /// <summary>Parses a trace from text. Not from a path -- see <see cref="DataText"/>.</summary>
        public static GoldenTrace Parse(string text) => Parse("golden trace", text);

        /// <summary>Parses a trace from UTF-8 bytes, which is what a caller that read a file holds.</summary>
        public static GoldenTrace ParseUtf8(byte[] utf8) => ParseUtf8("golden trace", utf8);

        /// <summary>Parses a trace, naming the content in any error message.</summary>
        public static GoldenTrace ParseUtf8(string source, byte[] utf8) =>
            Parse(source, DataText.FromUtf8(source, utf8));

        /// <summary>Parses a trace, naming the content in any error message.</summary>
        public static GoldenTrace Parse(string source, string text)
        {
            if (source is null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            string[] lines = DataText.SplitLines(text);
            var hashes = new List<ulong>();

            for (int index = 0; index < lines.Length; index++)
            {
                string line = lines[index];
                int number = index + 1;

                if (DataText.IsBlankOrComment(line))
                {
                    continue;
                }

                string[] fields = DataText.Fields(source, number, line);

                if (!string.Equals(fields[0], Keyword, StringComparison.Ordinal))
                {
                    throw new ContentException(
                        source,
                        number,
                        "starts with '" + fields[0] + "', but the only row a trace has is '" + Keyword + "'.");
                }

                if (fields.Length != FieldCount)
                {
                    throw DataText.WrongFieldCount(source, number, Keyword, FieldCount, fields.Length);
                }

                int tick = DataText.IntegerInRange(source, number, "the tick", fields[1], 0, int.MaxValue);

                if (tick != hashes.Count)
                {
                    throw new ContentException(
                        source,
                        number,
                        "is tick "
                        + tick.ToString(CultureInfo.InvariantCulture)
                        + " where the trace is up to tick "
                        + hashes.Count.ToString(CultureInfo.InvariantCulture)
                        + ". A trace runs from tick zero with no gaps: a missing tick is a tick nothing "
                        + "would be compared on, which is the one tick a divergence would then be free to "
                        + "start at.");
                }

                hashes.Add(DataText.Hex64(source, number, "the state hash", fields[2]));
            }

            if (hashes.Count == 0)
            {
                throw new ContentException(source, 0, "has no ticks in it at all.");
            }

            return new GoldenTrace(hashes.ToArray());
        }

        /// <summary>The state hash the trace recorded for a tick.</summary>
        public Hash64 At(int tick)
        {
            if (tick < 0 || tick >= _hashes.Length)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(tick),
                    "The trace covers ticks 0 to "
                    + FinalTick.ToString(CultureInfo.InvariantCulture)
                    + "; asked for tick "
                    + tick.ToString(CultureInfo.InvariantCulture)
                    + ".");
            }

            return Hash64.FromValue(_hashes[tick]);
        }

        /// <summary>
        /// Compares one tick, and throws naming the tick if it disagrees. A
        /// run driven through this a tick at a time stops at the first tick that
        /// differs rather than at the end.
        /// </summary>
        public void Check(int tick, Hash64 actual)
        {
            Hash64 expected = At(tick);

            if (expected != actual)
            {
                throw new DesyncException(tick, expected, actual);
            }
        }

        /// <summary>Renders a trace back to the text this parses, for whatever writes one.</summary>
        public static string Line(int tick, Hash64 hash) =>
            Keyword
            + " "
            + tick.ToString(CultureInfo.InvariantCulture)
            + " "
            + hash.ToString();
    }
}
