using System;
using System.Collections.Generic;
using System.Globalization;

namespace Sim
{
    /// <summary>
    /// A recorded run's rolling state hash, one entry per tick, to check a live
    /// run against as it goes. What it compares is internal simulation state
    /// rather than the snapshot. The file is generated by a real run and
    /// committed, not by whatever checks it.
    /// See <c>docs/adr/0004-rolling-state-hash-always-on.md</c>.
    /// </summary>
    public sealed class GoldenTrace
    {
        private const string Keyword = "tick";

        /// <summary>Fields per row, keyword included.</summary>
        private const int FieldCount = 3;

        /// <summary>The words a row here may open with. There is one.</summary>
        private static readonly string[] RowWords = { Keyword };

        private readonly ulong[] _hashes;

        private GoldenTrace(ulong[] hashes)
        {
            _hashes = hashes;
        }

        /// <summary>How many ticks the trace covers, counting tick zero.</summary>
        public int Count => _hashes.Length;

        /// <summary>The last tick in the trace, which is the tick the match ended on.</summary>
        public int FinalTick => _hashes.Length - 1;

        public static GoldenTrace Parse(string text) => Parse("golden trace", text);

        public static GoldenTrace ParseUtf8(byte[] utf8) => ParseUtf8("golden trace", utf8);

        public static GoldenTrace ParseUtf8(string source, byte[] utf8) =>
            Parse(source, DataText.FromUtf8(source, utf8));

        /// <summary>
        /// Parses <c>tick N HASH</c> rows, naming <paramref name="source"/> in any
        /// error. Ticks must run from zero with no gaps.
        /// </summary>
        public static GoldenTrace Parse(string source, string text)
        {
            if (source is null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            var hashes = new List<ulong>();

            foreach (DataText.Row row in DataText.Rows(source, text))
            {
                string[] fields = row.Fields;

                DataText.RequireRow(source, row, RowWords);

                if (fields.Length != FieldCount)
                {
                    throw DataText.WrongFieldCount(source, row.Line, Keyword, FieldCount, fields.Length);
                }

                int tick = DataText.IntegerInRange(source, row.Line, "the tick", fields[1], 0, int.MaxValue);

                if (tick != hashes.Count)
                {
                    throw new ContentException(
                        source,
                        row.Line,
                        "is tick "
                        + tick.ToString(CultureInfo.InvariantCulture)
                        + " where the trace is up to tick "
                        + hashes.Count.ToString(CultureInfo.InvariantCulture)
                        + ". A trace runs from tick zero with no gaps: a missing tick is a tick nothing "
                        + "would be compared on, which is the one tick a divergence would then be free to "
                        + "start at.");
                }

                hashes.Add(DataText.Hex64(source, row.Line, "the state hash", fields[2]));
            }

            if (hashes.Count == 0)
            {
                throw new ContentException(source, 0, "has no ticks in it at all.");
            }

            return new GoldenTrace(hashes.ToArray());
        }

        /// <summary>The state hash the trace recorded for a tick.</summary>
        public Hash64 At(int tick)
        {
            if (tick < 0 || tick >= _hashes.Length)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(tick),
                    "The trace covers ticks 0 to "
                    + FinalTick.ToString(CultureInfo.InvariantCulture)
                    + "; asked for tick "
                    + tick.ToString(CultureInfo.InvariantCulture)
                    + ".");
            }

            return Hash64.FromValue(_hashes[tick]);
        }

        /// <summary>Compares one tick, throwing a <see cref="DesyncException"/> naming it when it differs.</summary>
        public void Check(int tick, Hash64 actual)
        {
            Hash64 expected = At(tick);

            if (expected != actual)
            {
                throw new DesyncException(tick, expected, actual);
            }
        }

        /// <summary>Renders one row back to the text this parses.</summary>
        public static string Line(int tick, Hash64 hash) =>
            Keyword
            + " "
            + tick.ToString(CultureInfo.InvariantCulture)
            + " "
            + hash.ToString();
    }
}
