using System;
using System.IO;
using Tests.PlayMode;
using UnityEditor;
using UnityEngine;
using View;

namespace Tests.Fixtures
{
    /// <summary>
    /// Writes the assets the play-mode suite needs where there is no editor: the
    /// art manifest, and the oracle clips.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Both exist for the same reason, and it is the reason this ticket
    /// exists.</b> The suite used to sit behind <c>#if UNITY_EDITOR</c>, which
    /// deleted every test in it outside the editor and let the run report green
    /// having asserted nothing. Removing the <c>#if</c> means the two things it
    /// was hiding have to be got some other way:
    /// </para>
    /// <list type="bullet">
    /// <item><description>
    /// <b>The art</b>, which was loaded through <see cref="AssetDatabase"/> —
    /// which does not exist in a player. Resolved here once and written as
    /// serialized references, which a build carries.
    /// </description></item>
    /// <item><description>
    /// <b>The oracle clips</b>, which were built at runtime with
    /// <see cref="AnimationClip.SetCurve"/> — an editor-only call on a
    /// non-legacy clip. In a player it does nothing, logs <c>"Can't use
    /// AnimationClip::SetCurve at Runtime on non Legacy AnimationClips"</c>, and
    /// leaves an empty clip that poses everything at zero. Every sampling
    /// assertion then fails against its own oracle — watched, fourteen at once.
    /// So the curves are authored here, where <c>SetCurve</c> works, and the
    /// clips are committed.
    /// </description></item>
    /// </list>
    /// <para>
    /// Generated by a command and committed beside the change that caused them,
    /// like every other generated file in this repository. The art manifest has
    /// an edit-mode drift test; the clips need none, because their whole content
    /// is <i>x = 10t</i> and every test that loads one asserts exactly that. A
    /// clip that drifted from this file would fail the oracle by name.
    /// </para>
    /// <para>
    /// Runs headless, from a shell, with no editor session and nobody at a
    /// keyboard:
    /// </para>
    /// <code>
    /// Unity.exe -batchmode -quit -projectPath client \
    ///           -executeMethod Tests.Fixtures.GeneratedTestAssets.Run
    /// </code>
    /// </remarks>
    public static class GeneratedTestAssets
    {
        /// <summary>The folder Unity loads <c>Resources</c> assets out of.</summary>
        public const string ResourcesFolder = "Assets/Resources";

        /// <summary>Where the generated art manifest lands.</summary>
        public const string ManifestPath =
            ResourcesFolder + "/" + ResourcesMatchArtSource.ResourcePath + ".asset";

        /// <summary>The folder inside <c>Resources</c> the oracle clips land in.</summary>
        public const string ClipsFolder = ResourcesFolder + "/" + OracleClips.Folder;

        public static void Run()
        {
            WriteManifest();
            WriteOracleClips();

            AssetDatabase.SaveAssets();
        }

        private static void WriteManifest()
        {
            MatchArt art = ChosenArt.Load();

            if (!art.IsComplete)
            {
                throw new InvalidOperationException(
                    "ChosenArt resolved to an incomplete bundle — refusing to write " + ManifestPath);
            }

            EnsureFolder(ResourcesFolder);
            AssetDatabase.CreateAsset(MatchArtAsset.Holding(art), ManifestPath);
            AssetDatabase.SaveAssets();

            // Read back rather than trust the write. A ScriptableObject whose
            // references failed to serialize is a file that exists, loads, and
            // hands a player nothing but nulls -- which reaches the drawing code as
            // "nothing appeared" and says nothing about why.
            var written = AssetDatabase.LoadAssetAtPath<MatchArtAsset>(ManifestPath);

            if (written == null || !written.Art.IsComplete)
            {
                throw new InvalidOperationException(
                    ManifestPath + " was written but does not read back complete.");
            }

            Debug.Log("GeneratedTestAssets: wrote " + ManifestPath);
        }

        /// <summary>
        /// The three synthetic clips the sampling tests hold the graph to.
        /// </summary>
        /// <remarks>
        /// One channel each, on a child transform called <c>Bone</c>, so the
        /// correct pose at any time is a number this file can state and a test
        /// can assert. <see cref="OracleClips.Linear"/> is <i>x = 10t</i> over
        /// one second — the whole oracle. The two constants are what a mixer
        /// blend is measured between, because a blend of two moving clips has no
        /// fixed answer to compare against.
        /// </remarks>
        private static void WriteOracleClips()
        {
            EnsureFolder(ClipsFolder);

            Write(OracleClips.Linear, AnimationCurve.Linear(0f, 0f, OracleClips.Length, OracleClips.Travel));
            Write(OracleClips.ConstantZero, AnimationCurve.Constant(0f, OracleClips.Length, 0f));
            Write(OracleClips.ConstantTravel, AnimationCurve.Constant(0f, OracleClips.Length, OracleClips.Travel));
        }

        private static void Write(string name, AnimationCurve curve)
        {
            var clip = new AnimationClip { legacy = false };
            clip.SetCurve(OracleClips.BoneName, typeof(Transform), "localPosition.x", curve);

            string path = ClipsFolder + "/" + name + ".anim";
            AssetDatabase.CreateAsset(clip, path);

            Debug.Log("GeneratedTestAssets: wrote " + path);
        }

        private static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder))
            {
                return;
            }

            AssetDatabase.CreateFolder(
                Path.GetDirectoryName(folder).Replace('\\', '/'),
                Path.GetFileName(folder));
        }
    }
}
