using Sim;
using UnityEngine;

namespace View
{
    /// <summary>
    /// The one root object. Everything the scene contains hangs off this, and
    /// the camera, the light and the floor are built here at runtime.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Exactly one root, forever.</b> The alternative is a budget, and
    /// budgets get argued with one convenient object at a time — a manager
    /// here, a light probe there, and eventually the scene is the thing that
    /// decides what the game is, in a serialized format nobody reads and git
    /// cannot merge. One root makes the rule checkable by counting, and an
    /// edit-mode test counts it.
    /// </para>
    /// <para>
    /// <b>Nothing here is a simulation input.</b> This class reads the map
    /// through the simulation's parser and hands it to the floor; the camera it
    /// builds never travels the other way. See <see cref="IsometricCameraRig"/>.
    /// </para>
    /// <para>
    /// The two materials are serialized so a player build carries the shaders
    /// they use — a shader only ever reached through <c>Shader.Find</c> can be
    /// stripped out of a build and leave a magenta floor. When they are absent,
    /// as in a test that builds this object from nothing, plain ones are made
    /// on the spot from the same committed colours.
    /// </para>
    /// </remarks>
    [DisallowMultipleComponent]
    public sealed class MatchRoot : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Drawn on corridor cells. Generated by tools/build-match-scene.ps1.")]
        private Material roadMaterial;

        [SerializeField]
        [Tooltip("Drawn on every other cell. Generated by tools/build-match-scene.ps1.")]
        private Material grassMaterial;

        /// <summary>The parsed playfield, or null before <see cref="Build"/>.</summary>
        public HexMap Map { get; private set; }

        /// <summary>The floor, once it has been drawn.</summary>
        public HexFloor Floor { get; private set; }

        /// <summary>The camera rig, once it has been built.</summary>
        public IsometricCameraRig CameraRig { get; private set; }

        /// <summary>The one directional light.</summary>
        public Light Sun { get; private set; }

        /// <summary>The shared tile mesh every floor tile is drawn with.</summary>
        public Mesh TileMesh { get; private set; }

        private void Awake()
        {
            if (Floor == null)
            {
                Build(StreamingContent.ReadMap());
            }
        }

        /// <summary>
        /// Builds the whole playfield under this object: the floor from the
        /// map, then the light, then the camera framed on the floor.
        /// </summary>
        /// <remarks>
        /// Public and taking the map rather than reading it, so a test can draw
        /// a floor from a map it wrote itself without a file being involved.
        /// The order matters in one place only: the camera is framed on bounds
        /// the floor reports, so the floor goes first.
        /// </remarks>
        public void Build(HexMap map)
        {
            Map = map;
            TileMesh = HexTileMesh.Create();

            Floor = HexFloor.Build(
                transform,
                map,
                TileMesh,
                roadMaterial != null ? roadMaterial : ViewMaterials.Create("Road", SceneFraming.RoadColor),
                grassMaterial != null ? grassMaterial : ViewMaterials.Create("Grass", SceneFraming.GrassColor));

            Sun = BuildSun(transform);
            CameraRig = IsometricCameraRig.Build(transform, Floor.WorldBounds);
        }

        private static Light BuildSun(Transform parent)
        {
            var host = new GameObject("Sun");
            host.transform.SetParent(parent, worldPositionStays: false);
            host.transform.rotation = SceneFraming.SunRotation;

            var light = host.AddComponent<Light>();
            light.type = LightType.Directional;
            light.color = SceneFraming.SunColor;
            light.intensity = SceneFraming.SunIntensity;

            // Real shadows from real geometry. Nothing in this project paints
            // one on, so this is the only thing that makes a hex look solid.
            light.shadows = LightShadows.Soft;
            light.shadowStrength = SceneFraming.SunShadowStrength;

            return light;
        }
    }
}
