using System;
using UnityEngine;

namespace View
{
    /// <summary>
    /// Where a caller that is not a generated scene gets the match art from.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>This exists so the play-mode suite is not editor-only.</b> Loading the
    /// art used to mean <c>AssetDatabase</c>, which does not exist outside the
    /// editor, so every fixture that drew a match sat behind
    /// <c>#if UNITY_EDITOR</c> — and a test class inside a dead <c>#if</c>
    /// compiles to nothing, yields no tests, and lets the run report green
    /// having asserted nothing at all. That is not a hypothetical: this
    /// repository has killed the same species of silently-empty gate twice
    /// before. The seam removes the <c>#if</c> rather than remembering to check
    /// it.
    /// </para>
    /// <para>
    /// <b>Not how the game gets its art.</b> The match scene carries serialized
    /// references filled in by <c>MatchSceneBuilder</c>, and that stays exactly
    /// as it was — see <see cref="MatchArt"/> on why a runtime lookup would be
    /// the wrong thing there. This is the fixture's route to the same
    /// assets, for code that has no scene to be handed them by.
    /// </para>
    /// </remarks>
    public interface IMatchArtSource
    {
        /// <summary>The models and clips, or a throw naming what is missing.</summary>
        MatchArt Load();
    }

    /// <summary>
    /// The art source in force: an editor adapter when there is an editor, the
    /// player adapter otherwise.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The editor adapter registers itself on domain load, because the
    /// direction of the reference has to be that way round: the play-mode test
    /// assembly must compile with no editor assembly in sight, so it cannot be
    /// the one naming the adapter. What it names is this, which is ordinary
    /// runtime code, and which falls back to
    /// <see cref="ResourcesMatchArtSource"/> when nothing registered — that is,
    /// in a player.
    /// </para>
    /// </remarks>
    public static class MatchArtSource
    {
        private static IMatchArtSource _current = new ResourcesMatchArtSource();

        /// <summary>Installs an adapter. Called by the editor adapter on domain load.</summary>
        public static void Use(IMatchArtSource source)
            => _current = source ?? throw new ArgumentNullException(nameof(source));

        /// <summary>The models and clips, from whichever adapter is in force.</summary>
        public static MatchArt Load() => _current.Load();
    }

    /// <summary>
    /// The player adapter: the art out of a generated asset that survives into a
    /// build.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>A <c>Resources</c> folder, deliberately, and only here.</b> The
    /// objection to <c>Resources.Load</c> recorded on <see cref="MatchArt"/> is
    /// that it needs a magic folder and returns null when a path drifts — which
    /// is the right objection for the game, whose art is wired into a scene and
    /// checked when that scene is generated. It is the wrong objection for this,
    /// because a test build has no scene to be handed art by and
    /// <c>AssetDatabase</c> is not there to ask. What is there is whatever the
    /// build carried, and a <c>Resources</c> asset is the plainest way to make
    /// it carry something. The drift the objection warns about is answered the
    /// way this repository answers it everywhere else: the asset is generated by
    /// a command, committed beside the change, and an edit-mode test fails when
    /// it no longer matches what it was generated from.
    /// </para>
    /// </remarks>
    public sealed class ResourcesMatchArtSource : IMatchArtSource
    {
        /// <summary>The asset's path inside <c>Resources</c>, without extension.</summary>
        public const string ResourcePath = "MatchArt";

        /// <inheritdoc/>
        public MatchArt Load()
        {
            var asset = Resources.Load<MatchArtAsset>(ResourcePath);

            if (asset == null)
            {
                throw new InvalidOperationException(
                    "No MatchArt asset at Resources/" + ResourcePath + ". It is generated and committed — "
                    + "run tools/build-test-assets.ps1 and commit what it writes.");
            }

            return asset.Art;
        }
    }
}
