using Sim;
using UnityEngine;
using UnityEngine.UIElements;

namespace View
{
    /// <summary>
    /// The one root object. Everything the scene contains hangs off this, and
    /// the camera, the light and the floor are built here at runtime.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Exactly one root, forever.</b> The alternative is a budget, and
    /// budgets get argued with one convenient object at a time — a manager
    /// here, a light probe there, and eventually the scene is the thing that
    /// decides what the game is, in a serialized format nobody reads and git
    /// cannot merge. One root makes the rule checkable by counting, and an
    /// edit-mode test counts it.
    /// </para>
    /// <para>
    /// <b>Nothing here is a simulation input.</b> This class reads the map
    /// through the simulation's parser and hands it to the floor; the camera it
    /// builds never travels the other way. See <see cref="OrbitCameraRig"/>.
    /// </para>
    /// <para>
    /// The two materials are serialized so a player build carries the shaders
    /// they use — a shader only ever reached through <c>Shader.Find</c> can be
    /// stripped out of a build and leave a magenta floor. When they are absent,
    /// as in a test that builds this object from nothing, plain ones are made
    /// on the spot from the same committed colours.
    /// </para>
    /// </remarks>
    [DisallowMultipleComponent]
    public sealed class MatchRoot : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Drawn on corridor cells. Generated by tools/build-match-scene.ps1.")]
        private Material roadMaterial;

        [SerializeField]
        [Tooltip("Drawn on every other cell. Generated by tools/build-match-scene.ps1.")]
        private Material grassMaterial;

        [SerializeField]
        [Tooltip("The sky the camera clears to. Generated by tools/build-match-scene.ps1.")]
        private Material skyMaterial;

        [SerializeField]
        [Tooltip("The plain the board sits in. Generated by tools/build-match-scene.ps1.")]
        private Material landMaterial;

        [SerializeField]
        [Tooltip("The floor's six tile models and their atlas. Generated by tools/build-match-scene.ps1.")]
        private TileSet tiles = new TileSet();

        [SerializeField]
        [Tooltip("The models the board is dressed with. Optional: an empty set draws a bare board.")]
        private SceneryModels scenery = new SceneryModels();

        [SerializeField]
        [Tooltip("How heavily the board is dressed. Optional: unset is the shipped weight.")]
        private BoardDressingAsset dressing;

        [SerializeField]
        [Tooltip("The models and clips the match is drawn with. Every one chosen by the developer; see #44.")]
        private MatchArt art = new MatchArt();

        /// <summary>The parsed playfield, or null before <see cref="Build"/>.</summary>
        public HexMap Map { get; private set; }

        /// <summary>The floor, once it has been drawn.</summary>
        public HexFloor Floor { get; private set; }

        /// <summary>The camera rig, once it has been built.</summary>
        public OrbitCameraRig CameraRig { get; private set; }

        /// <summary>The one directional light.</summary>
        public Light Sun { get; private set; }

        /// <summary>The sky and the land around the board. Never null after a build.</summary>
        public Horizon Horizon { get; private set; }

        /// <summary>The shared tile mesh every floor tile is drawn with.</summary>
        public Mesh TileMesh { get; private set; }

        /// <summary>The match being drawn, once one has started.</summary>
        public MatchView MatchView { get; private set; }

        /// <summary>
        /// What decides which tick is on screen, once a match has started.
        /// </summary>
        public PlaybackController Playback { get; private set; }

        /// <summary>The scrub bar, once there is a match to scrub.</summary>
        public PlaybackControls Controls { get; private set; }

        /// <summary>The art the match is drawn with.</summary>
        public MatchArt Art => art;

        /// <summary>
        /// Build, commit, watch, ten waves — and which of those is on screen.
        /// Null until <see cref="BeginRun(ulong)"/>.
        /// </summary>
        public RunLoop Loop { get; private set; }

        /// <summary>
        /// The run the board is built against, once there is one.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The client holds the run, and the view still holds nothing</b> —
        /// ADR-0051. It lives out here beside the mode the player is in, not
        /// inside <see cref="MatchView"/>, because what a build phase draws from
        /// is a decision being composed rather than game state being simulated:
        /// no tick has seen it. <see cref="MatchView"/> still reads snapshots
        /// and nothing else, which is ADR-0007 untouched.
        /// </para>
        /// <para>
        /// <b>It is the loop's, and this is a reader.</b> What advances it is
        /// <see cref="RunLoop.Commit"/> and nothing else — see that class for
        /// why a phase reaching the simulation by any other route would be the
        /// one thing this architecture is built to prevent.
        /// </para>
        /// </remarks>
        public Run Run => Loop == null ? null : Loop.Run;

        /// <summary>
        /// The round being composed on screen, once there is a run: both halves
        /// of one build phase, over one purse.
        /// </summary>
        public ComposedRound Composing { get; private set; }

        /// <summary>What may be built, once there is a round to build in.</summary>
        public TowerPalette Palette { get; private set; }

        /// <summary>The board as it is being built, and the hex that lights.</summary>
        public BuildBoard Building { get; private set; }

        /// <summary>The wave being composed, once there is a round to compose one in.</summary>
        public WaveBar Wave { get; private set; }

        /// <summary>What turns a click into a build action.</summary>
        public BuildInput Pointer { get; private set; }

        /// <summary>
        /// The scene opens on the first round's build phase, and there is no
        /// match on screen until one has been committed.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The recorded match is not what a player sees any more.</b> It was,
        /// for the whole of the walking skeleton, and while the build chrome had
        /// no modes to switch between it went on playing underneath one — so a
        /// composed tower could be stood on a hex a recorded tower was already
        /// drawn on. Two things drawing one board is what the mode switch
        /// removes. The record is still read, for the playfield and for the
        /// seed; what is gone is the match built from it. It is still reachable
        /// through <see cref="BeginMatch(UnitTypeTable, Ruleset, ReplayBundle, MatchArt)"/>,
        /// which is what the frame capture draws.
        /// </para>
        /// <para>
        /// Missing content is reported and not thrown. A player whose streaming
        /// copy was never generated should show its playfield and say what is
        /// missing, rather than dying in <c>Awake</c> and leaving a scene that
        /// is half built for a reason nobody can see. The build gate is where a
        /// missing content file is supposed to be caught, and it is caught
        /// there.
        /// </para>
        /// </remarks>
        private void Awake()
        {
            // Read once, used twice. The floor is drawn from the record's own
            // inlined grid rather than from map.txt, because the floor and the
            // run have to be the same playfield and the only way to be certain
            // of that is for there to be one of them.
            ReplayBundle record = StreamingContent.HasEveryMatchFile()
                ? StreamingContent.ReadRecordedMatch()
                : null;

            if (Floor == null)
            {
                Build(record != null ? record.Map : StreamingContent.ReadMap());
            }

            if (record == null)
            {
                Debug.LogWarning(
                    "MatchRoot: no run started — the streaming copy is incomplete. Run "
                    + "tools/sync-streaming-content.ps1 and commit what it writes. Looked in "
                    + StreamingContent.Directory);

                return;
            }

            if (!art.IsComplete)
            {
                Debug.LogWarning(
                    "MatchRoot: no run started — the art is not wired up. The scene is generated: run "
                    + "tools/build-match-scene.ps1 and commit what it writes.");

                return;
            }

            if (Loop == null)
            {
                BeginRun(record.Seed);
            }
        }

        /// <summary>
        /// Stands a run up on the playfield this object already built, and opens
        /// its first build phase.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The seed is the record's, like the match's.</b> This assembly
        /// cannot read a clock and is not going to start: a run seeded from the
        /// wall clock would be a different game every time somebody pressed
        /// play, which is exactly the property that makes a playtest also a
        /// determinism test.
        /// </para>
        /// <para>
        /// <b>The field is the canned pairing</b> — the committed defense
        /// behind the canned round, which is the population
        /// <c>content/defense.txt</c> and <c>content/field.txt</c> describe.
        /// <b>Not <c>content/wave.txt</c></b>: that is a whole authored match
        /// and a run scored against one dies of health in round three. See
        /// <see cref="StreamingContent.FieldFileName"/>. The field is a number
        /// rather than anything on screen: the player watches one member of it,
        /// and what the wave got past all ten of them is what feeds the purse.
        /// </para>
        /// <para>
        /// <b>The run arrives as a way to make one, not as one already made.</b>
        /// Proving the session on the way out needs a second run on the same
        /// seed and the same shape that nothing has been played into, and a
        /// factory is the only thing that can hand back both.
        /// </para>
        /// </remarks>
        /// <param name="seed">The one seed every draw in the run is derived from.</param>
        public RunLoop BeginRun(ulong seed) =>
            BeginRun(seed, Application.persistentDataPath, art);

        /// <summary>
        /// The same, writing the session's script into a folder the caller names
        /// and drawing it with art the caller supplies.
        /// </summary>
        /// <remarks>
        /// What a test calls, for two reasons. The folder, so a run played by a
        /// test does not write over the one a person played; and the art, which
        /// is the same seam and the same reason as
        /// <see cref="BeginBuilding(ComposedRound, MatchArt)"/> — a caller that
        /// has the assets in hand and no generated scene to read them from would
        /// otherwise get nothing on exactly the checkout where somebody is
        /// trying to see whether the run works.
        /// </remarks>
        public RunLoop BeginRun(ulong seed, string directory, MatchArt art)
        {
            if (Map == null)
            {
                throw new System.InvalidOperationException(
                    "BeginRun was called before Build, so there is no playfield to run on.");
            }

            // One root plays one run, and a second call is loud rather than
            // quietly wrong. A second header is parented to this object rather
            // than to the loop, so it would outlive the call that failed and go
            // on drawing another run's numbers over the real ones — which reads
            // as a header that is simply wrong.
            if (Loop != null)
            {
                throw new System.InvalidOperationException(
                    "This root is already playing a run. A run does not survive quitting and there is no "
                    + "resuming one, so a second is a fresh scene rather than a second call.");
            }

            Loop = RunLoop.Build(this, art, () => RunOn(seed), directory);

            return Loop;
        }

        /// <summary>
        /// A run on <paramref name="seed"/> with nothing played into it, over
        /// this object's playfield and the shipped content.
        /// </summary>
        public Run RunOn(ulong seed)
        {
            UnitTypeTable types = StreamingContent.ReadUnitTypes();
            Ruleset rules = StreamingContent.ReadRuleset();
            UpgradeLadder ladder = StreamingContent.ReadUpgrades(types);

            return new Run(
                Map,
                rules,
                types,
                ladder,
                FieldPool.Canned(
                    Map,
                    rules,
                    types,
                    ladder,
                    StreamingContent.ReadDefense(types),
                    StreamingContent.ReadField(types)),
                seed);
        }

        /// <summary>
        /// Puts the build chrome up over a round the caller composed. What a
        /// test calls, with a run of its own or none at all.
        /// </summary>
        public void BeginBuilding(ComposedRound round) => BeginBuilding(round, art);

        /// <summary>
        /// The same, drawn with art the caller supplies rather than the art
        /// serialized on this object.
        /// </summary>
        /// <remarks>
        /// The same seam, for the same reason, as
        /// <see cref="BeginMatch(UnitTypeTable, Ruleset, TowerLayout, WaveScript, ulong, MatchArt)"/>:
        /// a caller that has the assets in hand and no generated scene to read
        /// them from would otherwise get an empty board on exactly the checkout
        /// where somebody is trying to see whether building works.
        /// </remarks>
        public void BeginBuilding(ComposedRound round, MatchArt art) =>
            BeginBuilding(round, art, otherChrome: null);

        /// <summary>
        /// The same, told about one more panel a click has to stop at.
        /// </summary>
        /// <param name="otherChrome">
        /// A panel that is up in build mode and is not the pointer's own — the
        /// header, whose button is the one thing on screen a click could reach
        /// through onto the board behind it. Null where there is none.
        /// </param>
        public void BeginBuilding(ComposedRound round, MatchArt art, UIDocument otherChrome)
        {
            if (round == null) throw new System.ArgumentNullException(nameof(round));
            if (art == null) throw new System.ArgumentNullException(nameof(art));

            if (Map == null)
            {
                throw new System.InvalidOperationException(
                    "BeginBuilding was called before Build, so there is no playfield to build on.");
            }

            if (Composing != null)
            {
                throw new System.InvalidOperationException(
                    "This root is already composing a round. A second set of build chrome over the first "
                    + "would leave two palettes selecting into two phases, only one of which anybody is "
                    + "going to commit. End the one that is up first.");
            }

            Composing = round;
            Building = BuildBoard.Build(transform, round, art, RoutePath.For(Map), TileMesh, Map, Floor);
            Palette = TowerPalette.Build(transform, round, CameraRig.Camera, Map);
            Wave = WaveBar.Build(transform, round);
            Pointer = BuildInput.Build(
                transform,
                round,
                Palette,
                Building,
                Wave,
                CameraRig.Camera,
                otherChrome);
        }

        /// <summary>
        /// Takes the build chrome down: the composed board, the palette, the
        /// wave bar and the pointer.
        /// </summary>
        /// <remarks>
        /// <b>Deactivated and then destroyed, in that order.</b>
        /// <see cref="Object.Destroy(Object)"/> is deferred to the end of the
        /// frame, so on its own it would leave the round's towers drawn over the
        /// watched match's for exactly as long as it takes the mode to
        /// change — which is the overlap this method exists to remove.
        /// Deactivating is what makes it immediate; destroying is what stops it
        /// leaking.
        /// </remarks>
        public void EndBuilding()
        {
            // The order is the order they were built in, reversed, and it buys
            // nothing beyond reading that way: Destroy is deferred, so not one
            // of these OnDestroy methods runs before this call returns, and
            // BuildInput's unsubscribes null-check the two objects it holds.
            Retire(Pointer);
            Retire(Wave);
            Retire(Palette);
            Retire(Building);

            Pointer = null;
            Wave = null;
            Palette = null;
            Building = null;
            Composing = null;
        }

        /// <summary>
        /// Puts a match a caller already built on screen, with the scrub bar
        /// over it. What the run loop calls with what
        /// <see cref="Run.MatchAt"/> handed back.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The match is read rather than advanced.</b> Seeking re-simulates
        /// from tick zero — ADR-0026 — so what a view has to remember about a
        /// match is the five things it was built from, and it builds its own
        /// from them. This one is therefore a description and is let go; asking
        /// twice is cheaper than remembering, which is the same reason
        /// <see cref="Run.MatchAt"/> rebuilds rather than keeps.
        /// </para>
        /// <para>
        /// The playfield is checked rather than taken. A match built over a
        /// different map than the floor under it would draw creeps walking a
        /// corridor that is not the one on screen, and nothing else in the
        /// project would notice.
        /// </para>
        /// </remarks>
        public MatchView BeginWatching(Match match, UnitTypeTable types, MatchArt art)
        {
            if (match == null) throw new System.ArgumentNullException(nameof(match));

            if (!ReferenceEquals(match.Map, Map))
            {
                throw new System.InvalidOperationException(
                    "This match is fought on a different playfield than the floor this root drew. One "
                    + "of the two is not the run's map, and drawing them together would put creeps on a "
                    + "corridor that is not the one under them.");
            }

            MatchView view = BeginMatch(types, match.Rules, match.Layout, match.Wave, match.Seed, art);

            // Built here and not in BeginMatch, because watching is what wants
            // them. The frame capture draws a match and photographs it, and a
            // scrub bar it never asked for is chrome standing over a picture.
            // They are wired to the view that exists when they are built, and
            // there is a new view every round, so they come and go with it.
            Playback = new PlaybackController(view);
            Controls = PlaybackControls.Build(transform, Playback);

            return view;
        }

        /// <summary>
        /// Starts the match a record describes, drawn with the art the caller
        /// supplies.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Two things have to happen in one order and this is the only place
        /// that knows it: the record is put through the replay gate, and then
        /// the match is built from what the record carries. Unpacking a bundle
        /// at a call site meant repeating both, and the half anybody would
        /// forget is the gate — which is the half that produces a refusal by
        /// name instead of a match played under a ruleset it was not recorded
        /// against.
        /// </para>
        /// <para>
        /// The gate's return value is dropped on purpose. What is wanted from
        /// it is the refusal; the view builds its own match, because a view
        /// that cannot build one cannot seek.
        /// </para>
        /// </remarks>
        public MatchView BeginMatch(UnitTypeTable types, Ruleset rules, ReplayBundle record, MatchArt art)
        {
            if (record == null) throw new System.ArgumentNullException(nameof(record));

            record.Replay(types, rules);

            return BeginMatch(
                types,
                rules,
                record.Ghost.ToLayout(types),
                record.Wave.ToScript(types),
                record.Seed,
                art);
        }

        /// <summary>
        /// Starts a match from content already parsed. What a test calls, and
        /// what the frame capture calls with art of its own.
        /// </summary>
        public MatchView BeginMatch(
            UnitTypeTable types,
            Ruleset rules,
            TowerLayout layout,
            WaveScript wave,
            ulong seed) =>
            BeginMatch(types, rules, layout, wave, seed, art);

        /// <summary>
        /// The same, drawn with art the caller supplies rather than the art
        /// serialized on this object.
        /// </summary>
        /// <remarks>
        /// For a caller that has the assets in hand and no generated scene to
        /// read them from — the frame capture, which has to work on a project
        /// whose scene has not been rebuilt yet, and would otherwise fail with
        /// "the art is not wired up" on exactly the checkout where somebody is
        /// trying to see whether the art works.
        /// </remarks>
        public MatchView BeginMatch(
            UnitTypeTable types,
            Ruleset rules,
            TowerLayout layout,
            WaveScript wave,
            ulong seed,
            MatchArt art)
        {
            if (Map == null)
            {
                throw new System.InvalidOperationException(
                    "BeginMatch was called before Build, so there is no playfield to draw a match on.");
            }

            // One root draws one match, and a second call is loud rather than
            // quietly wrong. The controls are wired to the view that exists
            // when they are built; replacing that view underneath them leaves a
            // scrub bar driving a match nobody is looking at, which looks
            // exactly like a scrub bar that does not work.
            if (MatchView != null)
            {
                throw new System.InvalidOperationException(
                    "This root is already drawing a match. Beginning a second one would leave the "
                    + "playback controls pointed at the first, which is a scrub bar that moves and "
                    + "changes nothing on screen.");
            }

            var host = new GameObject("Match");
            host.transform.SetParent(transform, worldPositionStays: false);

            MatchView = host.AddComponent<MatchView>();
            MatchView.Begin(Map, rules, types, layout, wave, seed, art);

            // The layout does not change for the life of a match, so the board
            // is dressed around it once rather than watched.
            Floor.ClearSceneryUnder(Standing(layout));

            return MatchView;
        }

        /// <summary>
        /// Takes the match and its scrub bar down, so a second one can go up.
        /// </summary>
        /// <remarks>
        /// Both together and neither alone: the controls hold the view they were
        /// built for, so a bar that outlived its match would drive a match
        /// nobody is looking at. Deactivated before destroying for the reason
        /// <see cref="EndBuilding"/> is — a deferred destroy leaves the finished
        /// round's creeps on the board for the frame the next one is composed
        /// in.
        /// </remarks>
        public void EndMatch()
        {
            Retire(Controls);
            Retire(MatchView);

            Controls = null;
            Playback = null;
            MatchView = null;

            // The felled groves grow back, so the next round is composed on the
            // board this one started from rather than on the one it left.
            if (Floor != null)
            {
                Floor.ClearSceneryUnder(null);
            }
        }

        /// <summary>Every cell a layout stands a tower on.</summary>
        private static System.Collections.Generic.IEnumerable<(int Column, int Row)> Standing(TowerLayout layout)
        {
            for (int index = 0; index < layout.Count; index++)
            {
                PlacedTower placed = layout.Towers[index];

                yield return (placed.Column, placed.Row);
            }
        }

        /// <summary>
        /// Takes one piece of chrome or one drawn thing off the screen now and
        /// out of memory at the end of the frame.
        /// </summary>
        private static void Retire(Component component)
        {
            if (component == null)
            {
                return;
            }

            component.gameObject.SetActive(false);
            Destroy(component.gameObject);
        }

        /// <summary>
        /// Builds the whole playfield under this object: the floor from the
        /// map, then the light, then the camera framed on the floor.
        /// </summary>
        /// <remarks>
        /// Public and taking the map rather than reading it, so a test can draw
        /// a floor from a map it wrote itself without a file being involved.
        /// The order matters in one place only: the camera is framed on bounds
        /// the floor reports, so the floor goes first.
        /// </remarks>
        public void Build(
            HexMap map,
            TileSet tiles = null,
            SceneryModels scenery = null,
            DressingSettings settings = null,
            BoardDressing authored = null,
            SkySettings sky = default)
        {
            Map = map;
            TileMesh = HexTileMesh.Create();

            Floor = HexFloor.Build(
                transform,
                map,
                TilesToDrawWith(tiles),
                SceneryToDressWith(scenery),
                settings ?? (dressing != null ? dressing.Settings() : null),
                authored ?? StreamingContent.ReadDressing());

            Sun = BuildSun(transform);

            // After the floor, because the horizon is hung at the height the
            // board's rim falls to and sized off how far it is across; before
            // the camera, because the camera has to be told whether there is a
            // sky to clear to.
            Horizon = View.Horizon.Build(
                transform,
                map,
                Floor.WorldBounds,
                settings ?? (dressing != null ? dressing.Settings() : null),
                skyMaterial,
                landMaterial,
                sky);

            CameraRig = OrbitCameraRig.Build(transform, Floor.WorldBounds);
            Horizon.Frame(CameraRig.Camera);
        }

        /// <summary>
        /// The tiles the floor is drawn from: the imported set if one is wired
        /// and complete, and the generated blockout otherwise.
        /// </summary>
        /// <remarks>
        /// The same shape as the material fields above — a serialized reference
        /// with a code-built fallback — so that a scene which has never been
        /// through <c>tools/build-match-scene.ps1</c> still draws a playfield,
        /// and a test can build one with no assets at all. A set that is present
        /// but half-filled falls back rather than drawing holes; see
        /// <see cref="TileSet.IsComplete"/>.
        /// </remarks>
        private TileSet TilesToDrawWith(TileSet supplied)
        {
            if (supplied != null && supplied.IsComplete)
            {
                return supplied;
            }

            if (tiles != null && tiles.IsComplete)
            {
                return tiles;
            }

            return TileSet.Blockout(
                TileMesh,
                roadMaterial != null ? roadMaterial : ViewMaterials.Create("Road", SceneFraming.RoadColor),
                grassMaterial != null ? grassMaterial : ViewMaterials.Create("Grass", SceneFraming.GrassColor));
        }

        /// <summary>
        /// The models the board is dressed with: the set handed in, then the one
        /// the scene carries, and nothing at all if neither is usable.
        /// </summary>
        /// <remarks>
        /// There is no generated fallback here, unlike <see cref="TilesToDrawWith"/>,
        /// and that is the difference between the two in one line: a floor
        /// without tiles cannot show where the path goes, and a floor without
        /// scenery is simply a floor.
        /// </remarks>
        private SceneryModels SceneryToDressWith(SceneryModels supplied)
        {
            if (supplied != null && supplied.IsUsable)
            {
                return supplied;
            }

            return scenery != null && scenery.IsUsable ? scenery : null;
        }

        private static Light BuildSun(Transform parent)
        {
            var host = new GameObject("Sun");
            host.transform.SetParent(parent, worldPositionStays: false);
            host.transform.rotation = SceneFraming.SunRotation;

            var light = host.AddComponent<Light>();
            light.type = LightType.Directional;
            light.color = SceneFraming.SunColor;
            light.intensity = SceneFraming.SunIntensity;

            // Real shadows from real geometry. Nothing in this project paints
            // one on, so this is the only thing that makes a hex look solid.
            light.shadows = LightShadows.Soft;
            light.shadowStrength = SceneFraming.SunShadowStrength;

            return light;
        }
    }
}
