using Sim;
using UnityEngine;

namespace View
{
    /// <summary>
    /// The one root object. Everything the scene contains hangs off this, and
    /// the camera, the light and the floor are built here at runtime.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Exactly one root, forever.</b> The alternative is a budget, and
    /// budgets get argued with one convenient object at a time — a manager
    /// here, a light probe there, and eventually the scene is the thing that
    /// decides what the game is, in a serialized format nobody reads and git
    /// cannot merge. One root makes the rule checkable by counting, and an
    /// edit-mode test counts it.
    /// </para>
    /// <para>
    /// <b>Nothing here is a simulation input.</b> This class reads the map
    /// through the simulation's parser and hands it to the floor; the camera it
    /// builds never travels the other way. See <see cref="OrbitCameraRig"/>.
    /// </para>
    /// <para>
    /// The two materials are serialized so a player build carries the shaders
    /// they use — a shader only ever reached through <c>Shader.Find</c> can be
    /// stripped out of a build and leave a magenta floor. When they are absent,
    /// as in a test that builds this object from nothing, plain ones are made
    /// on the spot from the same committed colours.
    /// </para>
    /// </remarks>
    [DisallowMultipleComponent]
    public sealed class MatchRoot : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Drawn on corridor cells. Generated by tools/build-match-scene.ps1.")]
        private Material roadMaterial;

        [SerializeField]
        [Tooltip("Drawn on every other cell. Generated by tools/build-match-scene.ps1.")]
        private Material grassMaterial;

        [SerializeField]
        [Tooltip("The models and clips the match is drawn with. Every one chosen by the developer; see #44.")]
        private MatchArt art = new MatchArt();

        /// <summary>The parsed playfield, or null before <see cref="Build"/>.</summary>
        public HexMap Map { get; private set; }

        /// <summary>The floor, once it has been drawn.</summary>
        public HexFloor Floor { get; private set; }

        /// <summary>The camera rig, once it has been built.</summary>
        public OrbitCameraRig CameraRig { get; private set; }

        /// <summary>The one directional light.</summary>
        public Light Sun { get; private set; }

        /// <summary>The shared tile mesh every floor tile is drawn with.</summary>
        public Mesh TileMesh { get; private set; }

        /// <summary>The match being drawn, once one has started.</summary>
        public MatchView MatchView { get; private set; }

        /// <summary>
        /// What decides which tick is on screen, once a match has started.
        /// </summary>
        public PlaybackController Playback { get; private set; }

        /// <summary>The scrub bar, once there is a match to scrub.</summary>
        public PlaybackControls Controls { get; private set; }

        /// <summary>The art the match is drawn with.</summary>
        public MatchArt Art => art;

        /// <summary>
        /// The run the board is built against, once there is one.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The client holds the run, and the view still holds nothing</b> --
        /// ADR-0051. It lives out here on the root beside the mode the player is
        /// in, not inside <see cref="MatchView"/>, because what a build phase
        /// draws from is a decision being composed rather than game state being
        /// simulated: no tick has seen it. <see cref="MatchView"/> still reads
        /// snapshots and nothing else, which is ADR-0007 untouched.
        /// </para>
        /// <para>
        /// <b>Nothing here advances it.</b> Committing a round is
        /// <see cref="Run.Advance"/>, and the loop that presses it -- build,
        /// commit, watch, ten waves -- is #198. What this file does is stand the
        /// run up and point the palette and the pointer at it, which is what
        /// makes the board clickable.
        /// </para>
        /// </remarks>
        public Run Run { get; private set; }

        /// <summary>The round being composed on screen, once there is a run.</summary>
        public ComposedRound Composing { get; private set; }

        /// <summary>What may be built, once there is a round to build in.</summary>
        public TowerPalette Palette { get; private set; }

        /// <summary>The board as it is being built, and the hex that lights.</summary>
        public BuildBoard Building { get; private set; }

        /// <summary>What turns a click into a build action.</summary>
        public BuildInput Pointer { get; private set; }

        private void Awake()
        {
            // Read once, used twice. The floor is drawn from the record's own
            // inlined grid rather than from map.txt, because the floor and the
            // match have to be the same playfield and the only way to be certain
            // of that is for there to be one of them. Where there is no record
            // to read, the authored map still draws a floor and BeginMatch says
            // what is missing.
            ReplayBundle record = StreamingContent.HasEveryMatchFile()
                ? StreamingContent.ReadRecordedMatch()
                : null;

            if (Floor == null)
            {
                Build(record != null ? record.Map : StreamingContent.ReadMap());
            }

            if (MatchView == null)
            {
                BeginMatch(record);
            }

            // Only when there is a match. A run that could not read its content
            // or its art has already said so, and a scrub bar over nothing is a
            // second, quieter way of reporting the same thing.
            if (MatchView != null && Controls == null)
            {
                Playback = new PlaybackController(MatchView);
                Controls = PlaybackControls.Build(transform, Playback);
            }

            // Same two conditions as the match: a run needs the content, and
            // drawing what it builds needs the art. A checkout missing either
            // has already said so once, and a palette listing towers that cannot
            // be drawn would be a second, quieter way of reporting it.
            if (record != null && art.IsComplete && Run == null)
            {
                BeginBuilding(record.Seed);
            }
        }

        /// <summary>
        /// Stands up a run on the playfield this object already built, and puts
        /// the palette, the board and the pointer over it.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The seed is the record's, like the match's.</b> This assembly
        /// cannot read a clock and is not going to start: a run seeded from the
        /// wall clock would be a different game every time somebody pressed
        /// play, which is exactly the property that makes a playtest also a
        /// determinism test. See <see cref="BeginMatch(ReplayBundle)"/>, which
        /// takes its seed from the same place for the same reason.
        /// </para>
        /// <para>
        /// <b>The field is the canned pairing</b> -- the committed defense
        /// against the committed wave, which is the population
        /// <c>content/defense.txt</c> and <c>content/wave.txt</c> describe. It
        /// is what a round is scored against, and it is a number rather than
        /// anything on screen until #198 draws a header.
        /// </para>
        /// </remarks>
        /// <param name="seed">The one seed every draw in the run is derived from.</param>
        public void BeginBuilding(ulong seed)
        {
            UnitTypeTable types = StreamingContent.ReadUnitTypes();

            Run = new Run(
                Map,
                StreamingContent.ReadRuleset(),
                types,
                StreamingContent.ReadUpgrades(types),
                FieldPool.Canned(StreamingContent.ReadDefense(types), StreamingContent.ReadWave(types)),
                seed);

            BeginBuilding(ComposedRound.For(Run));
        }

        /// <summary>
        /// The same, over a round the caller composed. What a test calls, with a
        /// run of its own or none at all.
        /// </summary>
        public void BeginBuilding(ComposedRound round) => BeginBuilding(round, art);

        /// <summary>
        /// The same, drawn with art the caller supplies rather than the art
        /// serialized on this object.
        /// </summary>
        /// <remarks>
        /// The same seam, for the same reason, as
        /// <see cref="BeginMatch(UnitTypeTable, Ruleset, TowerLayout, WaveScript, ulong, MatchArt)"/>:
        /// a caller that has the assets in hand and no generated scene to read
        /// them from would otherwise get an empty board on exactly the checkout
        /// where somebody is trying to see whether building works.
        /// </remarks>
        public void BeginBuilding(ComposedRound round, MatchArt art)
        {
            if (round == null) throw new System.ArgumentNullException(nameof(round));
            if (art == null) throw new System.ArgumentNullException(nameof(art));

            if (Map == null)
            {
                throw new System.InvalidOperationException(
                    "BeginBuilding was called before Build, so there is no playfield to build on.");
            }

            Composing = round;
            Building = BuildBoard.Build(transform, round, art, RoutePath.For(Map), TileMesh);
            Palette = TowerPalette.Build(transform, round, CameraRig.Camera);
            Pointer = BuildInput.Build(
                transform,
                round,
                Palette,
                Building,
                CameraRig.Camera,
                Controls != null ? Controls.Document : null);
        }

        /// <summary>
        /// Starts the recorded match on the floor this object already built.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Separate from <see cref="Build"/>, and deliberately so. The floor is
        /// drawable from a map alone, which is what lets a test write four rows
        /// of characters and check the tiles; a match needs the type table and a
        /// record as well. Folding the two together would make every floor test
        /// depend on content it does not care about.
        /// </para>
        /// <para>
        /// <b>The match on screen is the recorded one, seed included.</b> Which
        /// match this is decides what every tick number in
        /// <c>docs/sit-down.md</c> means: the checklist is written against
        /// <c>content/landmarks.txt</c>, and that table is what a real run of
        /// these exact bytes reported. A seed serialized on this object instead
        /// would be a second copy of a number that already lives in the record —
        /// and the two the project actually had differed by eleven ticks on the
        /// last creep to die, which does not look wrong from the screen and
        /// simply sends somebody to the wrong second of the match.
        /// </para>
        /// <para>
        /// Missing content is reported and not thrown. A player whose streaming
        /// copy was never generated should show its playfield and say what is
        /// missing, rather than dying in <c>Awake</c> and leaving a scene that
        /// is half built for a reason nobody can see. The build gate is where a
        /// missing content file is supposed to be caught, and it is caught
        /// there.
        /// </para>
        /// </remarks>
        /// <param name="record">
        /// The recorded match, or null when the streaming copy is incomplete.
        /// </param>
        public void BeginMatch(ReplayBundle record)
        {
            if (record == null)
            {
                Debug.LogWarning(
                    "MatchRoot: no match drawn — the streaming copy is incomplete. Run "
                    + "tools/sync-streaming-content.ps1 and commit what it writes. Looked in "
                    + StreamingContent.Directory);

                return;
            }

            if (!art.IsComplete)
            {
                Debug.LogWarning(
                    "MatchRoot: no match drawn — the art is not wired up. The scene is generated: run "
                    + "tools/build-match-scene.ps1 and commit what it writes.");

                return;
            }

            BeginMatch(StreamingContent.ReadUnitTypes(), StreamingContent.ReadRuleset(), record, art);
        }

        /// <summary>
        /// Starts the match a record describes, drawn with the art the caller
        /// supplies.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Two things have to happen in one order and this is the only place
        /// that knows it: the record is put through the replay gate, and then
        /// the match is built from what the record carries. Unpacking a bundle
        /// at a call site meant repeating both, and the half anybody would
        /// forget is the gate — which is the half that produces a refusal by
        /// name instead of a match played under a ruleset it was not recorded
        /// against.
        /// </para>
        /// <para>
        /// The gate's return value is dropped on purpose. What is wanted from
        /// it is the refusal; the view builds its own match, because a view
        /// that cannot build one cannot seek.
        /// </para>
        /// </remarks>
        public MatchView BeginMatch(UnitTypeTable types, Ruleset rules, ReplayBundle record, MatchArt art)
        {
            if (record == null) throw new System.ArgumentNullException(nameof(record));

            record.Replay(types, rules);

            return BeginMatch(
                types,
                rules,
                record.Ghost.ToLayout(types),
                record.Wave.ToScript(types),
                record.Seed,
                art);
        }

        /// <summary>
        /// Starts a match from content already parsed. What a test calls, and
        /// what the frame capture calls with art of its own.
        /// </summary>
        public MatchView BeginMatch(
            UnitTypeTable types,
            Ruleset rules,
            TowerLayout layout,
            WaveScript wave,
            ulong seed) =>
            BeginMatch(types, rules, layout, wave, seed, art);

        /// <summary>
        /// The same, drawn with art the caller supplies rather than the art
        /// serialized on this object.
        /// </summary>
        /// <remarks>
        /// For a caller that has the assets in hand and no generated scene to
        /// read them from — the frame capture, which has to work on a project
        /// whose scene has not been rebuilt yet, and would otherwise fail with
        /// "the art is not wired up" on exactly the checkout where somebody is
        /// trying to see whether the art works.
        /// </remarks>
        public MatchView BeginMatch(
            UnitTypeTable types,
            Ruleset rules,
            TowerLayout layout,
            WaveScript wave,
            ulong seed,
            MatchArt art)
        {
            if (Map == null)
            {
                throw new System.InvalidOperationException(
                    "BeginMatch was called before Build, so there is no playfield to draw a match on.");
            }

            // One root draws one match, and a second call is loud rather than
            // quietly wrong. The controls are wired to the view that exists
            // when they are built; replacing that view underneath them leaves a
            // scrub bar driving a match nobody is looking at, which looks
            // exactly like a scrub bar that does not work.
            if (MatchView != null)
            {
                throw new System.InvalidOperationException(
                    "This root is already drawing a match. Beginning a second one would leave the "
                    + "playback controls pointed at the first, which is a scrub bar that moves and "
                    + "changes nothing on screen.");
            }

            var host = new GameObject("Match");
            host.transform.SetParent(transform, worldPositionStays: false);

            MatchView = host.AddComponent<MatchView>();
            MatchView.Begin(Map, rules, types, layout, wave, seed, art);

            return MatchView;
        }

        /// <summary>
        /// Builds the whole playfield under this object: the floor from the
        /// map, then the light, then the camera framed on the floor.
        /// </summary>
        /// <remarks>
        /// Public and taking the map rather than reading it, so a test can draw
        /// a floor from a map it wrote itself without a file being involved.
        /// The order matters in one place only: the camera is framed on bounds
        /// the floor reports, so the floor goes first.
        /// </remarks>
        public void Build(HexMap map)
        {
            Map = map;
            TileMesh = HexTileMesh.Create();

            Floor = HexFloor.Build(
                transform,
                map,
                TileMesh,
                roadMaterial != null ? roadMaterial : ViewMaterials.Create("Road", SceneFraming.RoadColor),
                grassMaterial != null ? grassMaterial : ViewMaterials.Create("Grass", SceneFraming.GrassColor));

            Sun = BuildSun(transform);
            CameraRig = OrbitCameraRig.Build(transform, Floor.WorldBounds);
        }

        private static Light BuildSun(Transform parent)
        {
            var host = new GameObject("Sun");
            host.transform.SetParent(parent, worldPositionStays: false);
            host.transform.rotation = SceneFraming.SunRotation;

            var light = host.AddComponent<Light>();
            light.type = LightType.Directional;
            light.color = SceneFraming.SunColor;
            light.intensity = SceneFraming.SunIntensity;

            // Real shadows from real geometry. Nothing in this project paints
            // one on, so this is the only thing that makes a hex look solid.
            light.shadows = LightShadows.Soft;
            light.shadowStrength = SceneFraming.SunShadowStrength;

            return light;
        }
    }
}
