using System.IO;
using Sim;
using UnityEngine;

namespace View
{
    /// <summary>
    /// The view side of "the simulation never opens a file": this reads the
    /// bytes, the simulation parses them.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>The simulation has no path-shaped hole in it.</b> Every parser in
    /// <c>Sim.dll</c> takes text or bytes and nothing takes a file name, which
    /// is the only reason the assembly can be scanned for banned constructs and
    /// the only reason it has no <c>System.IO</c> reference. Somebody has to
    /// read the disk, and it is this class.
    /// </para>
    /// <para>
    /// <b>Content lives in streaming assets because a build has no repository.</b>
    /// Double-click the player on a machine that never cloned this project and
    /// <c>../../content/map.txt</c> is not there — there is no relative path
    /// back, and there is not going to be one. Streaming assets are the folder
    /// Unity copies into the player verbatim, so the same bytes are beside the
    /// executable as were beside the source.
    /// </para>
    /// <para>
    /// The copy under <c>Assets/StreamingAssets/</c> is generated by
    /// <c>tools/sync-streaming-content.ps1</c> and committed, exactly like a
    /// lockfile: the authored original in <c>content/</c> is the source of
    /// truth, the copy is what ships, and an edit-mode test fails if they have
    /// drifted apart. Regenerating it is a command; noticing it needs
    /// regenerating is not left to anybody's memory.
    /// </para>
    /// </remarks>
    public static class StreamingContent
    {
        /// <summary>
        /// The folder inside streaming assets that the generated copy lands in.
        /// </summary>
        public const string FolderName = "content";

        /// <summary>The authored map grid.</summary>
        public const string MapFileName = "map.txt";

        /// <summary>The unit type table — both creep types and both tower types.</summary>
        public const string UnitsFileName = "units.txt";

        /// <summary>The six towers the match is fought by.</summary>
        public const string DefenseFileName = "defense.txt";

        /// <summary>The orders the match is fought against.</summary>
        public const string WaveFileName = "wave.txt";

        /// <summary>
        /// Every content file the player has to be able to read, in the order a
        /// match needs them: the types first, because the defense and the wave
        /// are both parsed against them.
        /// </summary>
        /// <remarks>
        /// The same list <c>tools/sync-streaming-content.ps1</c> copies, and an
        /// edit-mode test checks the two agree. A file in one and not the other
        /// is either content that ships and is never read, or content that is
        /// read and does not ship — the second of which presents as an empty
        /// playfield in a build that worked perfectly in the editor.
        /// </remarks>
        public static readonly string[] MatchFileNames =
        {
            MapFileName,
            UnitsFileName,
            DefenseFileName,
            WaveFileName,
        };

        /// <summary>Where the generated copies are, at runtime and in the editor.</summary>
        public static string Directory => Path.Combine(Application.streamingAssetsPath, FolderName);

        /// <summary>The full path of one content file.</summary>
        public static string PathOf(string fileName) => Path.Combine(Directory, fileName);

        /// <summary>
        /// The bytes of one content file. Throws naming the path it looked at,
        /// because a missing content file in a build is the failure that
        /// otherwise presents as an empty screen.
        /// </summary>
        public static byte[] Read(string fileName)
        {
            string path = PathOf(fileName);

            if (!File.Exists(path))
            {
                throw new FileNotFoundException(
                    "No content at " + path + ". Run tools/sync-streaming-content.ps1 and commit what it writes.",
                    path);
            }

            return File.ReadAllBytes(path);
        }

        /// <summary>
        /// The playfield, parsed by the simulation's own parser — corridor
        /// assertion and map hash included. There is no view-side map reader
        /// and there is not going to be one.
        /// </summary>
        public static HexMap ReadMap() => HexMap.ParseUtf8(MapFileName, Read(MapFileName));

        /// <summary>The unit type table, parsed by the simulation.</summary>
        public static UnitTypeTable ReadUnitTypes() =>
            UnitTypeTable.ParseUtf8(UnitsFileName, Read(UnitsFileName));

        /// <summary>The defense, parsed against <paramref name="types"/>.</summary>
        public static TowerLayout ReadDefense(UnitTypeTable types) =>
            TowerLayout.ParseUtf8(DefenseFileName, Read(DefenseFileName), types);

        /// <summary>The wave, parsed against <paramref name="types"/>.</summary>
        public static WaveScript ReadWave(UnitTypeTable types) =>
            WaveScript.ParseUtf8(WaveFileName, Read(WaveFileName), types);

        /// <summary>
        /// True when every file a match needs is beside the player.
        /// </summary>
        /// <remarks>
        /// Asked before starting a match rather than caught afterwards, so a
        /// project whose streaming copy was never generated draws its floor and
        /// says why the match did not start — instead of throwing out of
        /// <c>Awake</c> and leaving a scene that is half built for a reason
        /// nobody can see.
        /// </remarks>
        public static bool HasEveryMatchFile()
        {
            foreach (string fileName in MatchFileNames)
            {
                if (!File.Exists(PathOf(fileName)))
                {
                    return false;
                }
            }

            return true;
        }
    }
}
