using System.IO;
using Sim;
using UnityEngine;

namespace View
{
    /// <summary>
    /// The view side of "the simulation never opens a file": this reads the
    /// bytes, the simulation parses them.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>The simulation has no path-shaped hole in it.</b> Every parser in
    /// <c>Sim.dll</c> takes text or bytes and nothing takes a file name, which
    /// is the only reason the assembly can be scanned for banned constructs and
    /// the only reason it has no <c>System.IO</c> reference. Somebody has to
    /// read the disk, and it is this class.
    /// </para>
    /// <para>
    /// <b>Content lives in streaming assets because a build has no repository.</b>
    /// Double-click the player on a machine that never cloned this project and
    /// <c>../../content/map.txt</c> is not there — there is no relative path
    /// back, and there is not going to be one. Streaming assets are the folder
    /// Unity copies into the player verbatim, so the same bytes are beside the
    /// executable as were beside the source.
    /// </para>
    /// <para>
    /// The copy under <c>Assets/StreamingAssets/</c> is generated by
    /// <c>tools/sync-streaming-content.ps1</c> and committed, exactly like a
    /// lockfile: the authored original in <c>content/</c> is the source of
    /// truth, the copy is what ships, and an edit-mode test fails if they have
    /// drifted apart. Regenerating it is a command; noticing it needs
    /// regenerating is not left to anybody's memory.
    /// </para>
    /// </remarks>
    public static class StreamingContent
    {
        /// <summary>
        /// The folder inside streaming assets that the generated copy lands in.
        /// </summary>
        public const string FolderName = "content";

        /// <summary>The authored map grid.</summary>
        public const string MapFileName = "map.txt";

        /// <summary>Where the generated copies are, at runtime and in the editor.</summary>
        public static string Directory => Path.Combine(Application.streamingAssetsPath, FolderName);

        /// <summary>The full path of one content file.</summary>
        public static string PathOf(string fileName) => Path.Combine(Directory, fileName);

        /// <summary>
        /// The bytes of one content file. Throws naming the path it looked at,
        /// because a missing content file in a build is the failure that
        /// otherwise presents as an empty screen.
        /// </summary>
        public static byte[] Read(string fileName)
        {
            string path = PathOf(fileName);

            if (!File.Exists(path))
            {
                throw new FileNotFoundException(
                    "No content at " + path + ". Run tools/sync-streaming-content.ps1 and commit what it writes.",
                    path);
            }

            return File.ReadAllBytes(path);
        }

        /// <summary>
        /// The playfield, parsed by the simulation's own parser — corridor
        /// assertion and map hash included. There is no view-side map reader
        /// and there is not going to be one.
        /// </summary>
        public static HexMap ReadMap() => HexMap.ParseUtf8(MapFileName, Read(MapFileName));
    }
}
