using System.IO;
using Sim;
using UnityEngine;

namespace View
{
    /// <summary>
    /// The view side of "the simulation never opens a file": this reads the
    /// bytes, the simulation parses them.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>The simulation has no path-shaped hole in it.</b> Every parser in
    /// <c>Sim.dll</c> takes text or bytes and nothing takes a file name, which
    /// is the only reason the assembly can be scanned for banned constructs and
    /// the only reason it has no <c>System.IO</c> reference. Somebody has to
    /// read the disk, and it is this class.
    /// </para>
    /// <para>
    /// <b>Content lives in streaming assets because a build has no repository.</b>
    /// Double-click the player on a machine that never cloned this project and
    /// <c>../../content/map.txt</c> is not there — there is no relative path
    /// back, and there is not going to be one. Streaming assets are the folder
    /// Unity copies into the player verbatim, so the same bytes are beside the
    /// executable as were beside the source.
    /// </para>
    /// <para>
    /// The copy under <c>Assets/StreamingAssets/</c> is generated by
    /// <c>tools/sync-streaming-content.ps1</c> and committed, exactly like a
    /// lockfile: the authored original in <c>content/</c> is the source of
    /// truth, the copy is what ships, and an edit-mode test fails if they have
    /// drifted apart. Regenerating it is a command; noticing it needs
    /// regenerating is not left to anybody's memory.
    /// </para>
    /// </remarks>
    public static class StreamingContent
    {
        /// <summary>
        /// The folder inside streaming assets that the generated copy lands in.
        /// </summary>
        public const string FolderName = "content";

        /// <summary>The authored map grid.</summary>
        public const string MapFileName = "map.txt";

        /// <summary>The unit type table — both creep types and both tower types.</summary>
        public const string UnitsFileName = "units.txt";

        /// <summary>Which unit follows which: the upgrade ladder.</summary>
        /// <remarks>
        /// <para>
        /// <b>It ships twice over.</b> The client reads the edges — a build phase
        /// is refused against them, so a <see cref="Sim.Run"/> is handed a ladder
        /// and the client has to have one; see <see cref="ReadUpgrades"/>. And
        /// the ladder is folded into the unit table's content hash, which is what
        /// <see cref="Sim.ReplayBundle.Replay"/> compares the record's stamped one
        /// against. A player without this file rebuilds the wrong hash and the
        /// shipped record is refused at the gate — which presents as a floor that
        /// draws and a match that never starts.
        /// </para>
        /// <para>
        /// So a checkout missing it fails twice over, and only one of the two
        /// looks like a missing file: the client cannot compose a round at all,
        /// and the shipped record is refused at the gate — which presents as a
        /// floor that draws and a match that never starts.
        /// </para>
        /// </remarks>
        public const string UpgradesFileName = "upgrades.txt";

        /// <summary>The six towers the match is fought by.</summary>
        public const string DefenseFileName = "defense.txt";

        /// <summary>The orders the match is fought against.</summary>
        public const string WaveFileName = "wave.txt";

        /// <summary>
        /// Every number a shot resolves through: the damage matrix, the armour
        /// expression and the floor.
        /// </summary>
        /// <remarks>
        /// The tick loop reads it on every landing, so a player without it can
        /// draw a floor and never resolve a hit. It ships beside the unit table
        /// for the same reason that one does: the record inlines a defense and a
        /// wave, and neither of the two tables they are read against.
        /// </remarks>
        public const string RulesetFileName = "ruleset.txt";

        /// <summary>
        /// The whole match in one run of bytes: the seed, the map, the defense
        /// and the wave. What the player actually plays.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>The player plays the record, not a seed of its own.</b> The
        /// committed landmark table — the ticks the sit-down checklist sends
        /// somebody to look at — is what a real run of <i>these bytes</i>
        /// reported. A player that re-derived the same match from the text
        /// files would need the seed written down a second time, and a second
        /// copy of a number is a number that goes out of date: the two differ by
        /// eleven ticks on the last creep to die, which is not a difference
        /// anybody would notice from the screen, only from being sent to the
        /// wrong second of the match.
        /// </para>
        /// <para>
        /// So the seed is not a field anywhere on the view side. It is read out
        /// of the record, along with the map, the defense and the wave, which is
        /// the same thing <c>ParityRunTests</c> does with the same bytes.
        /// </para>
        /// </remarks>
        public const string ReplayFileName = "match.replay";

        /// <summary>
        /// Every content file the player has to be able to read, in the order a
        /// match needs them: the types first, because the defense and the wave
        /// are both parsed against them.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The same list <c>tools/sync-streaming-content.ps1</c> copies, and an
        /// edit-mode test checks the two agree. A file in one and not the other
        /// is either content that ships and is never read, or content that is
        /// read and does not ship — the second of which presents as an empty
        /// playfield in a build that worked perfectly in the editor.
        /// </para>
        /// <para>
        /// The six text files ship alongside the record even though the record
        /// inlines three of them. <see cref="UnitsFileName"/>,
        /// <see cref="UpgradesFileName"/> and <see cref="RulesetFileName"/> have
        /// to: the type table and the ladder folded into it are what the replay
        /// gate checks the record's content hash against, and the ruleset is what
        /// every landing is resolved through. None of the three is in the bundle.
        /// The other three are the authored originals the bundle was recorded
        /// from, and they are what the fixtures read; the record's own gate is
        /// what stops the match on screen being drawn from anything else.
        /// </para>
        /// </remarks>
        public static readonly string[] MatchFileNames =
        {
            MapFileName,
            UnitsFileName,
            UpgradesFileName,
            RulesetFileName,
            DefenseFileName,
            WaveFileName,
            ReplayFileName,
        };

        /// <summary>Where the generated copies are, at runtime and in the editor.</summary>
        public static string Directory => Path.Combine(Application.streamingAssetsPath, FolderName);

        /// <summary>The full path of one content file.</summary>
        public static string PathOf(string fileName) => Path.Combine(Directory, fileName);

        /// <summary>
        /// The bytes of one content file. Throws naming the path it looked at,
        /// because a missing content file in a build is the failure that
        /// otherwise presents as an empty screen.
        /// </summary>
        public static byte[] Read(string fileName)
        {
            string path = PathOf(fileName);

            if (!File.Exists(path))
            {
                throw new FileNotFoundException(
                    "No content at " + path + ". Run tools/sync-streaming-content.ps1 and commit what it writes.",
                    path);
            }

            return File.ReadAllBytes(path);
        }

        /// <summary>
        /// The playfield, parsed by the simulation's own parser — corridor
        /// assertion and map hash included. There is no view-side map reader
        /// and there is not going to be one.
        /// </summary>
        public static HexMap ReadMap() => HexMap.ParseUtf8(MapFileName, Read(MapFileName));

        /// <summary>
        /// The unit type table, parsed by the simulation, with the upgrade ladder
        /// folded into its content hash.
        /// </summary>
        /// <remarks>
        /// The view reads no edge here — it reconstructs a hash. That hash is
        /// what the replay gate compares the shipped record's stamped one
        /// against, and the ladder is part of what it is made of, so a table
        /// returned without it is a table the record will be refused against.
        /// </remarks>
        public static UnitTypeTable ReadUnitTypes()
        {
            UnitTypeTable types = UnitTypeTable.ParseUtf8(UnitsFileName, Read(UnitsFileName));

            return types.WithLadder(ReadUpgrades(types));
        }

        /// <summary>
        /// The upgrade ladder itself, parsed against
        /// <paramref name="types"/>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// A run is handed one because <see cref="Sim.BuildPhase.Resolve"/> asks
        /// it which rows may be placed and which may be climbed into, so the
        /// client needs the object and not only the hash it contributes.
        /// </para>
        /// <para>
        /// It is one reading of one file either way: <see cref="ReadUnitTypes"/>
        /// folds the result of this call into the table's content hash, so the
        /// ladder a run enforces and the ladder the replay gate checks against
        /// cannot be two different opinions about the same bytes.
        /// </para>
        /// </remarks>
        public static UpgradeLadder ReadUpgrades(UnitTypeTable types) =>
            UpgradeLadder.ParseUtf8(UpgradesFileName, Read(UpgradesFileName), types);

        /// <summary>The rules every shot in a match is resolved through.</summary>
        public static Ruleset ReadRuleset() =>
            Ruleset.ParseUtf8(RulesetFileName, Read(RulesetFileName));

        /// <summary>The defense, parsed against <paramref name="types"/>.</summary>
        public static TowerLayout ReadDefense(UnitTypeTable types) =>
            TowerLayout.ParseUtf8(DefenseFileName, Read(DefenseFileName), types);

        /// <summary>The wave, parsed against <paramref name="types"/>.</summary>
        public static WaveScript ReadWave(UnitTypeTable types) =>
            WaveScript.ParseUtf8(WaveFileName, Read(WaveFileName), types);

        /// <summary>
        /// The recorded match, read but not yet gated: the bytes the command
        /// line replayed, beside the player.
        /// </summary>
        /// <remarks>
        /// Reading and replaying are separate gates in the simulation, and this
        /// is only the first — the record is readable here whatever ruleset it
        /// was made against. What refuses a record this build cannot honour is
        /// <c>ReplayBundle.Replay</c>, and it refuses by name.
        /// </remarks>
        public static ReplayBundle ReadRecordedMatch() =>
            ReplayBundle.FromBytes(FolderName + "/" + ReplayFileName, Read(ReplayFileName));

        /// <summary>
        /// True when every file a match needs is beside the player.
        /// </summary>
        /// <remarks>
        /// Asked before starting a match rather than caught afterwards, so a
        /// project whose streaming copy was never generated draws its floor and
        /// says why the match did not start — instead of throwing out of
        /// <c>Awake</c> and leaving a scene that is half built for a reason
        /// nobody can see.
        /// </remarks>
        public static bool HasEveryMatchFile()
        {
            foreach (string fileName in MatchFileNames)
            {
                if (!File.Exists(PathOf(fileName)))
                {
                    return false;
                }
            }

            return true;
        }
    }
}
