using System.Diagnostics;

namespace Sim.Tests;

/// <summary>
/// Where the things the gate tests actually live, and how to build the ones
/// that have to be built fresh.
/// </summary>
/// <remarks>
/// Paths are discovered by walking up from the test binary rather than being
/// passed in, so the gate runs the same way from a shell, from an IDE and from
/// continuous integration. Every lookup throws with the path it looked for if
/// it fails: a gate that silently skips is a gate that is green for no reason.
/// </remarks>
public static class RepoLayout
{
    private static readonly Lazy<string> LazyRoot = new(FindRoot);

    private static readonly Lazy<string> LazyFreshSim = new(() => Build(SimProject, "sim"));

    private static readonly Lazy<string> LazyPoison = new(() => Build(PoisonProject, "poison"));

    /// <summary>The repository root.</summary>
    public static string Root => LazyRoot.Value;

    /// <summary>The simulation's sources and project file.</summary>
    public static string SimDirectory => Path.Combine(Root, "sim");

    public static string SimProject => Path.Combine(SimDirectory, "Sim.csproj");

    public static string PoisonProject => Path.Combine(Root, "sim.poison", "Sim.Poison.csproj");

    /// <summary>
    /// The committed content. The simulation never learns these paths: the
    /// tests read the files and hand the text over, which is exactly what the
    /// engine and the command line will do, and the only reason the parsers
    /// can live inside an assembly that may not reference System.IO.
    /// </summary>
    public static string ContentDirectory => Path.Combine(Root, "content");

    public static string UnitsFile => Path.Combine(ContentDirectory, "units.txt");

    public static string WaveFile => Path.Combine(ContentDirectory, "wave.txt");

    public static string MapFile => Path.Combine(ContentDirectory, "map.txt");

    public static string DefenseFile => Path.Combine(ContentDirectory, "defense.txt");

    /// <summary>
    /// The rolling state hash of the committed match, one line per tick, as a
    /// real run produced it. Not authored, and not regenerated by anything that
    /// checks it -- a trace written by the run it validates is a test that
    /// cannot fail.
    /// </summary>
    public static string GoldenTraceFile => Path.Combine(ContentDirectory, "golden-trace.txt");

    /// <summary>
    /// The interesting ticks of the committed match, as the command line
    /// reported them from the event stream. Committed for the same reason the
    /// trace is: the sit-down checklist is written against these numbers, and
    /// nobody knows them until the match runs.
    /// </summary>
    public static string LandmarksFile => Path.Combine(ContentDirectory, "landmarks.txt");

    /// <summary>
    /// The committed replay bundle: the whole match in one run of bytes,
    /// written by the record verb of the command line and not by hand.
    /// </summary>
    public static string BundleFile => Path.Combine(ContentDirectory, "match.replay");

    /// <summary>The headless runner's project.</summary>
    public static string CliProject => Path.Combine(Root, "simcli", "Sim.Cli.csproj");

    /// <summary>Every committed data file that holds numbers, and must therefore hold no decimal point.</summary>
    public static IEnumerable<string> NumericContentFiles
    {
        get
        {
            yield return UnitsFile;
            yield return WaveFile;
            yield return DefenseFile;
        }
    }

    /// <summary>
    /// The assembly as it exists in the repository. This -- not a fresh build
    /// -- is what the behavioural tests link against, because bytes that only
    /// ever exist on a build machine are bytes nobody has checked.
    /// </summary>
    public static string CommittedAssembly =>
        Path.Combine(Root, "client", "Packages", "com.ssalter.sim", "Runtime", "Sim.dll");

    /// <summary>The committed debug symbols, beside the assembly where the debugger needs them.</summary>
    public static string CommittedSymbols =>
        Path.Combine(Root, "client", "Packages", "com.ssalter.sim", "Runtime", "Sim.pdb");

    /// <summary>
    /// A build of the simulation from the sources as they stand right now,
    /// into scratch space. Built once per test run.
    /// </summary>
    public static string FreshlyBuiltAssembly => Path.Combine(LazyFreshSim.Value, "Sim.dll");

    /// <summary>The poison assembly, built the same way and referenced by nothing.</summary>
    public static string PoisonAssembly => Path.Combine(LazyPoison.Value, "Sim.Poison.dll");

    /// <summary>
    /// Builds a project into scratch space and returns the output directory.
    /// The output goes to a temporary directory on purpose: building into the
    /// committed plug-in folder would have the gate rewrite the artefact it is
    /// supposed to be checking, which is the shape of a test that cannot fail.
    /// </summary>
    public static string Build(string projectPath, string label, string configuration = "Debug")
    {
        string output = Path.Combine(Path.GetTempPath(), "sim-build-gate", label);

        if (Directory.Exists(output))
        {
            Directory.Delete(output, recursive: true);
        }

        Directory.CreateDirectory(output);

        var startInfo = new ProcessStartInfo("dotnet")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            WorkingDirectory = Root,
        };

        startInfo.ArgumentList.Add("build");
        startInfo.ArgumentList.Add(projectPath);
        startInfo.ArgumentList.Add("--configuration");
        startInfo.ArgumentList.Add(configuration);
        startInfo.ArgumentList.Add("--output");
        startInfo.ArgumentList.Add(output);
        startInfo.ArgumentList.Add("--nologo");
        startInfo.Environment["MSBUILDDISABLENODEREUSE"] = "1";

        using Process process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Could not start dotnet build.");

        string standardOutput = process.StandardOutput.ReadToEnd();
        string standardError = process.StandardError.ReadToEnd();
        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"dotnet build failed for {projectPath} (exit {process.ExitCode}).{Environment.NewLine}"
                + standardOutput
                + standardError);
        }

        return output;
    }

    private static string FindRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "sim", "Sim.csproj")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException(
            "Could not find the repository root by walking up from "
            + AppContext.BaseDirectory
            + " looking for sim/Sim.csproj.");
    }
}
