using System.Diagnostics;
using Sim.Cli;

namespace Sim.Tests;

/// <summary>
/// Where the things the gate tests actually live, and how to build the ones
/// that have to be built fresh.
/// </summary>
/// <remarks>
/// Paths are discovered by walking up from the test binary rather than being
/// passed in, so the gate runs the same way from a shell, from an IDE and from
/// continuous integration. Every lookup throws with the path it looked for if
/// it fails: a gate that silently skips is a gate that is green for no reason.
/// </remarks>
public static class RepoLayout
{
    private static readonly Lazy<string> LazyRoot = new(FindRoot);

    private static readonly Lazy<string> LazyFreshSim = new(() => Build(SimProject, "sim"));

    private static readonly Lazy<string> LazyPoison = new(() => Build(PoisonProject, "poison"));

    /// <summary>The repository root.</summary>
    public static string Root => LazyRoot.Value;

    /// <summary>The simulation's sources and project file.</summary>
    public static string SimDirectory => Path.Combine(Root, "sim");

    public static string SimProject => Path.Combine(SimDirectory, "Sim.csproj");

    public static string PoisonProject => Path.Combine(Root, "sim.poison", "Sim.Poison.csproj");

    /// <summary>
    /// The committed content. The simulation never learns these paths: the
    /// tests read the files and hand the text over, which is exactly what the
    /// engine and the command line will do, and the only reason the parsers
    /// can live inside an assembly that may not reference System.IO.
    /// </summary>
    public static string ContentDirectory => Path.Combine(Root, "content");

    /// <summary>
    /// One of the seven files a run is built from, where this repository keeps
    /// it.
    /// </summary>
    /// <remarks>
    /// The name comes off <see cref="RunContentFiles"/> -- the runner's own
    /// declaration, compiled into this project as a source -- rather than being
    /// spelled again here. A gate checking one file while the command line reads
    /// another is green about content nobody plays.
    /// </remarks>
    internal static string InContent(ContentFile file) => Path.Combine(ContentDirectory, file.FileName);

    public static string UnitsFile => InContent(RunContentFiles.Units);

    /// <summary>
    /// The skeleton's authored match: a whole wave released over time, which is
    /// what <c>record</c> takes as <c>--wave</c>. No run verb reads it -- see
    /// <see cref="FieldFile"/> for the one that stands in for a stored round --
    /// so it is named here rather than declared with the seven.
    /// </summary>
    public static string WaveFile => Path.Combine(ContentDirectory, "wave.txt");

    /// <summary>
    /// Which unit follows which: one row per upgrade edge, both ends naming a
    /// row of <see cref="UnitsFile"/>. Read and handed over as text, exactly
    /// like the unit table, and legal with no edges in it at all.
    /// </summary>
    public static string UpgradesFile => InContent(RunContentFiles.Upgrades);

    public static string MapFile => InContent(RunContentFiles.Map);

    public static string DefenseFile => InContent(RunContentFiles.Defense);

    /// <summary>
    /// The wave the sweep's canned field sends: a build phase's output rather
    /// than the skeleton's authored match, which is a distinction that file's
    /// own header explains at length.
    /// </summary>
    public static string FieldFile => InContent(RunContentFiles.Field);

    /// <summary>
    /// Every number the rules are made of: the damage matrix, the armour
    /// expression, the floor, the purse, the offering and the scouting price.
    /// Read and handed over as text, exactly like the unit table.
    /// </summary>
    public static string RulesetFile => InContent(RunContentFiles.Rules);

    /// <summary>
    /// The shape: which waves are anchors, which tier each draws from, which one
    /// opens the steep counter, and the tier pools a run's filling is drawn
    /// from. Read and handed over as text, exactly like the unit table.
    /// </summary>
    public static string ScheduleFile => InContent(RunContentFiles.Schedule);

    /// <summary>
    /// The rolling state hash of the committed match, one line per tick, as a
    /// real run produced it. Not authored, and not regenerated by anything that
    /// checks it -- a trace written by the run it validates is a test that
    /// cannot fail.
    /// </summary>
    public static string GoldenTraceFile => Path.Combine(ContentDirectory, "golden-trace.txt");

    /// <summary>
    /// The interesting ticks of the committed match, as the command line
    /// reported them from the event stream. Committed for the same reason the
    /// trace is: the sit-down checklist is written against these numbers, and
    /// nobody knows them until the match runs.
    /// </summary>
    public static string LandmarksFile => Path.Combine(ContentDirectory, "landmarks.txt");

    /// <summary>
    /// The committed replay bundle: the whole match in one run of bytes,
    /// written by the record verb of the command line and not by hand.
    /// </summary>
    public static string BundleFile => Path.Combine(ContentDirectory, "match.replay");

    /// <summary>
    /// A run's build phases as somebody authored them: one row per round, in
    /// the same integers-only text every other content file is written in.
    /// </summary>
    public static string CommandScriptFile => Path.Combine(ContentDirectory, "commands.txt");

    /// <summary>
    /// The committed command stream: a whole run in one run of bytes, compiled
    /// from the script by the record-run verb of the command line and proved by
    /// being played before it was written.
    /// </summary>
    public static string CommandFile => Path.Combine(ContentDirectory, "run.commands");

    /// <summary>
    /// What that run came to, round by round, as a real play of the committed
    /// record produced it. Committed for the reason the golden trace is, one
    /// level up: nobody knows a run's vector until the run is played, and
    /// nothing that checks this file regenerates it.
    /// </summary>
    public static string RunOutcomeFile => Path.Combine(ContentDirectory, "run-outcome.txt");

    /// <summary>
    /// The committed balance report: what the sweep said about the roster the
    /// last time somebody regenerated it.
    /// </summary>
    /// <remarks>
    /// Committed for the reason the run outcome is, one level up again: nobody
    /// knows a creep's win rate until a few hundred runs of it have been played,
    /// so a retune that moves the roster's ranking is a diff here rather than an
    /// argument. Nothing that checks this file produces it --
    /// <c>tools/run-sweep.ps1 -Regenerate</c> is the only writer.
    /// </remarks>
    public static string SweepFile => Path.Combine(ContentDirectory, "sweep.csv");

    /// <summary>
    /// The twelve-row eyeball checklist, and the one artefact in this
    /// repository whose correctness is a human's job.
    /// </summary>
    /// <remarks>
    /// It is here, in an engine-free gate, because the thing that can go wrong
    /// with it is not engine-shaped: its rows name tick numbers taken from the
    /// committed landmark table, and a content change that moves a moment
    /// leaves those numbers pointing at the wrong second of the match. Nothing
    /// about that looks wrong to the person reading the checklist, which is why
    /// it is checked here rather than noticed there.
    /// </remarks>
    public static string SitDownFile => Path.Combine(Root, "docs", "sit-down.md");

    /// <summary>
    /// One tiny replay bundle per defense record format version that has ever
    /// shipped, and the result a real run of each produced.
    /// </summary>
    /// <remarks>
    /// <b>These files are committed forever.</b> The writer emits the current
    /// format version and nothing else, so an older bundle is not something
    /// this repository can produce again -- it can only be kept. They are the
    /// whole evidence that the reader branch for a retired version still reads,
    /// and deleting one is deleting the only test of that branch there will ever
    /// be.
    /// </remarks>
    public static string GoldenDirectory => Path.Combine(ContentDirectory, "golden");

    /// <summary>The committed bundle whose defense is at this format version.</summary>
    public static string GoldenBundleFile(int defenseFormatVersion) =>
        Path.Combine(GoldenDirectory, "defense-" + Number(defenseFormatVersion) + ".replay");

    /// <summary>What a real run of that bundle printed, committed beside it.</summary>
    public static string GoldenResultFile(int defenseFormatVersion) =>
        Path.Combine(GoldenDirectory, "defense-" + Number(defenseFormatVersion) + ".result");

    /// <summary>
    /// The unit type table that bundle was recorded against, copied beside it
    /// and never rewritten afterwards.
    /// </summary>
    /// <remarks>
    /// The replay gate refuses a record whose stamped content hash is not the
    /// hash of the table handed to it, so a golden checked against
    /// <see cref="UnitsFile"/> is a golden the next retune retires -- and a
    /// re-recorded one is a bundle at the current version, which is the one
    /// thing an older version's golden cannot be. The copy here is the table
    /// whose hash is in that bundle's header. The gate compares the same two
    /// things it always compares; what it compares against is now a file no
    /// content edit reaches.
    /// </remarks>
    public static string GoldenUnitsFile(int defenseFormatVersion) =>
        Path.Combine(GoldenDirectory, "defense-" + Number(defenseFormatVersion) + ".units");

    /// <summary>
    /// The upgrade ladder that bundle was recorded against, copied beside it and
    /// never rewritten afterwards.
    /// </summary>
    /// <remarks>
    /// <b>This file does not exist for every version, and its absence is
    /// meaningful rather than missing.</b> A bundle recorded before
    /// <c>content/upgrades.txt</c> existed was recorded against no ladder at all,
    /// so nothing folds into the hash in its header -- which is exactly what
    /// keeps that frozen hash standing forever. Whatever reads this asks whether
    /// the file is there and folds nothing when it is not.
    /// </remarks>
    public static string GoldenUpgradesFile(int defenseFormatVersion) =>
        Path.Combine(GoldenDirectory, "defense-" + Number(defenseFormatVersion) + ".upgrades");

    /// <summary>The headless runner's project.</summary>
    public static string CliProject => Path.Combine(Root, "simcli", "Sim.Cli.csproj");

    /// <summary>Every committed data file that holds numbers, and must therefore hold no decimal point.</summary>
    /// <remarks>
    /// Derived from <see cref="ContentParsers.All"/> rather than listed here, so
    /// that this and the hostile-locale sweep cannot drift apart. A content file
    /// arrives with a parser, and the two gates a parser owes -- no decimal point
    /// in the committed bytes, and the same digest under a hostile culture -- are
    /// both taken from the one declaration.
    /// </remarks>
    public static IEnumerable<string> NumericContentFiles
    {
        get
        {
            foreach (ContentParser parser in ContentParsers.All)
            {
                if (parser.IntegersOnly)
                {
                    yield return parser.File;
                }
            }
        }
    }

    /// <summary>
    /// The assembly as it exists in the repository. This -- not a fresh build
    /// -- is what the behavioural tests link against, because bytes that only
    /// ever exist on a build machine are bytes nobody has checked.
    /// </summary>
    public static string CommittedAssembly =>
        Path.Combine(Root, "client", "Packages", "com.ssalter.sim", "Runtime", "Sim.dll");

    /// <summary>The committed debug symbols, beside the assembly where the debugger needs them.</summary>
    public static string CommittedSymbols =>
        Path.Combine(Root, "client", "Packages", "com.ssalter.sim", "Runtime", "Sim.pdb");

    /// <summary>
    /// A build of the simulation from the sources as they stand right now,
    /// into scratch space. Built once per test run.
    /// </summary>
    public static string FreshlyBuiltAssembly => Path.Combine(LazyFreshSim.Value, "Sim.dll");

    /// <summary>The poison assembly, built the same way and referenced by nothing.</summary>
    public static string PoisonAssembly => Path.Combine(LazyPoison.Value, "Sim.Poison.dll");

    /// <summary>
    /// Builds a project into scratch space and returns the output directory.
    /// The output goes to a temporary directory on purpose: building into the
    /// committed plug-in folder would have the gate rewrite the artefact it is
    /// supposed to be checking, which is the shape of a test that cannot fail.
    /// </summary>
    public static string Build(string projectPath, string label, string configuration = "Debug")
    {
        string output = Path.Combine(Path.GetTempPath(), "sim-build-gate", label);

        if (Directory.Exists(output))
        {
            Directory.Delete(output, recursive: true);
        }

        Directory.CreateDirectory(output);

        var startInfo = new ProcessStartInfo("dotnet")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            WorkingDirectory = Root,
        };

        startInfo.ArgumentList.Add("build");
        startInfo.ArgumentList.Add(projectPath);
        startInfo.ArgumentList.Add("--configuration");
        startInfo.ArgumentList.Add(configuration);
        startInfo.ArgumentList.Add("--output");
        startInfo.ArgumentList.Add(output);
        startInfo.ArgumentList.Add("--nologo");
        startInfo.Environment["MSBUILDDISABLENODEREUSE"] = "1";

        using Process process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Could not start dotnet build.");

        // Drained at once rather than one after the other, for the reason
        // TheCommandLine.Invoke spells out: a pipe holds a few kilobytes, and a
        // build whose diagnostics outgrow one would hang here instead of failing.
        Task<string> standardOutput = process.StandardOutput.ReadToEndAsync();
        Task<string> standardError = process.StandardError.ReadToEndAsync();

        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"dotnet build failed for {projectPath} (exit {process.ExitCode}).{Environment.NewLine}"
                + standardOutput.Result
                + standardError.Result);
        }

        return output;
    }

    private static string Number(int value) =>
        value.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string FindRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "sim", "Sim.csproj")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException(
            "Could not find the repository root by walking up from "
            + AppContext.BaseDirectory
            + " looking for sim/Sim.csproj.");
    }
}
